/********************************************************************
*
* This file is part of the TeXnicCenter-system
*
* Copyright (C) 1999-2000 Sven Wiegand
* Copyright (C) 2000-$CurrentYear$ ToolsCenter
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation; either version 2 of
* the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*
* If you have further questions or if you want to support
* further TeXnicCenter development, visit the TeXnicCenter-homepage
*
*    http://www.ToolsCenter.org
*
*********************************************************************/

import "oaidl.idl";
import "ocidl.idl";

[
	object, uuid(EE616400-575E-11d5-A222-006097239934),
	helpstring("Provides access to TeXnicCenter's current project")
]
interface IProject : IUnknown
{
	[propget, helpstring("The path to the project's directory")] 
	HRESULT Path([out, retval] BSTR *path);

	[propget, helpstring("The project's title")]
	HRESULT Title([out, retval] BSTR *title);

	[propget, helpstring("Full path to the project's main file")]
	HRESULT MainFile([out, retval] BSTR *mainFile);

	[propget, helpstring("Specifies whether the project uses BibTeX or not")]
	HRESULT UsesBibTex([out, retval] BOOL *usesBibTex);

	[propput, helpstring("Specifies whether the project uses BibTeX or not")]
	HRESULT UsesBibTex([in] BOOL usesBibTex);

	[propget, helpstring("Specifies whether the project uses MakeIndex or not")]
	HRESULT UsesMakeIndex([out, retval] BOOL *usesMakeIndex);

	[propput, helpstring("Specifies whether the project uses MakeIndex or not")]
	HRESULT UsesMakeIndex([in] BOOL usesMakeIndex);
};