#pragma once

#include <vector>
#include <memory>

#include "OutputFilter.h"

/// Represents an output filter for messages generated by BibTeX.
class BibTeXOutputFilter : 
	public COutputFilter
{
	std::vector<CString> fileNames_;

	std::auto_ptr<COutputInfo> last_entry_;
	const tregex warning_line_;
	const tregex error_line_;
	const tregex database_file_;

public:
	BibTeXOutputFilter();
	~BibTeXOutputFilter();

protected:
	DWORD ParseLine(const CString& line, DWORD cookie);
	BOOL OnTerminate();

public:
	CString GetResultString();
};
