#pragma once

/**
 * @brief Possible BibTeX entry types.
 *
 * The types @ref BIBTEX_ENTRY_TYPE_ERROR and @ref BIBTEX_ENTRY_TYPE_UNKNOWN are
 * for internal use only.
 */
enum BibTeXEntryType
{
	BIBTEX_ENTRY_TYPE_UNKNOWN,
	BIBTEX_ENTRY_TYPE_ARTICLE,
	BIBTEX_ENTRY_TYPE_ARTWORK,
	BIBTEX_ENTRY_TYPE_AUDIO,
	BIBTEX_ENTRY_TYPE_BOOK,
	BIBTEX_ENTRY_TYPE_BOOKINBOOK,
	BIBTEX_ENTRY_TYPE_BOOKLET,
	BIBTEX_ENTRY_TYPE_COLLECTION,
	BIBTEX_ENTRY_TYPE_COMMENT,
	BIBTEX_ENTRY_TYPE_COMMENTARY,
	BIBTEX_ENTRY_TYPE_CONFERENCE,
	BIBTEX_ENTRY_TYPE_CUSTOM_A,
	BIBTEX_ENTRY_TYPE_CUSTOM_B,
	BIBTEX_ENTRY_TYPE_CUSTOM_C,
	BIBTEX_ENTRY_TYPE_CUSTOM_D,
	BIBTEX_ENTRY_TYPE_CUSTOM_E,
	BIBTEX_ENTRY_TYPE_CUSTOM_F,
	BIBTEX_ENTRY_TYPE_ELECTRONIC,
	BIBTEX_ENTRY_TYPE_IMAGE,
	BIBTEX_ENTRY_TYPE_INBOOK,
	BIBTEX_ENTRY_TYPE_INCOLLECTION,
	BIBTEX_ENTRY_TYPE_INPROCEEDINGS,
	BIBTEX_ENTRY_TYPE_INREFERENCE,
	BIBTEX_ENTRY_TYPE_JURISDICTION,
	BIBTEX_ENTRY_TYPE_LEGAL,
	BIBTEX_ENTRY_TYPE_LEGISLATION,
	BIBTEX_ENTRY_TYPE_LETTER,
	BIBTEX_ENTRY_TYPE_MANUAL,
	BIBTEX_ENTRY_TYPE_MASTERTHESIS,
	BIBTEX_ENTRY_TYPE_MISC,
	BIBTEX_ENTRY_TYPE_MOVIE,
	BIBTEX_ENTRY_TYPE_MUSIC,
	BIBTEX_ENTRY_TYPE_ONLINE,
	BIBTEX_ENTRY_TYPE_PATENT,
	BIBTEX_ENTRY_TYPE_PERFORMANCE,
	BIBTEX_ENTRY_TYPE_PERIODICAL,
	BIBTEX_ENTRY_TYPE_PHDTHESIS,
	BIBTEX_ENTRY_TYPE_PREAMBLE,
	BIBTEX_ENTRY_TYPE_PROCEEDINGS,
	BIBTEX_ENTRY_TYPE_REFERENCE,
	BIBTEX_ENTRY_TYPE_REPORT,
	BIBTEX_ENTRY_TYPE_REVIEW,
	BIBTEX_ENTRY_TYPE_SET,
	BIBTEX_ENTRY_TYPE_SOFTWARE,
	BIBTEX_ENTRY_TYPE_STANDARD,
	BIBTEX_ENTRY_TYPE_STRING,
	BIBTEX_ENTRY_TYPE_SUPPBOOK,
	BIBTEX_ENTRY_TYPE_SUPPCOLLECTION,
	BIBTEX_ENTRY_TYPE_SUPPPERIODICAL,
	BIBTEX_ENTRY_TYPE_TECHREPORT,
	BIBTEX_ENTRY_TYPE_THESIS,
	BIBTEX_ENTRY_TYPE_UNPUBLISHED,
	BIBTEX_ENTRY_TYPE_VIDEO,
	BIBTEX_ENTRY_TYPE_WWW
};

/**
 * @brief Returns the string representation of the specified enumeration value.
 */
CString GetString(BibTeXEntryType type);

/**
 * @brief Returns the appropriate @ref BibTeXEntryType value represented by the
 *        specified @a text.
 *
 * @exception std::invalid_argument Thrown if the specified @a text cannot be
 *            converted to @ref BibTeXEntryType.
 */
BibTeXEntryType GetBibTeXEntryTypeFromString(const CString& text);
