//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TeXnicCenter.rc
//
#define IDR_MAINFRAME                   1
#define ID_VIEW_BOOKMARKS_PANE          11
#define IDR_BIB_VIEW                    14
#define IDB_SPLASH                      69
#define IDI_ICON1                       72
#define IDR_POPUP_TOOLBAR               80
#define IDR_FORMAT_RECENTLY_USED        88
#define IDR_INSERT                      90
#define IDB_LIGHTBULB                   102
#define CG_IDS_TIPOFTHEDAY              104
#define CG_IDS_TIPOFTHEDAYMENU          105
#define CG_IDS_DIDYOUKNOW               106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDS_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define STE_TIP_FILE                    110
#define STE_URL_CANNOTOPEN              111
#define IDS_OPEN                        112
#define IDS_SAVE                        113
#define STE_WARNING_COUNT               114
#define IDB_DOCUMENTTYPES_LARGE         118
#define IDR_OUTPUT_BAR                  120
#define IDR_NAVIGATION_BAR              127
#define IDR_TEXT_BACK_COLOR             129
#define IDR_TEXT_FORE_COLOR             130
#define IDR_IDENTIFIERS                 133
#define IDR_POPUP_EDITOR                137
#define IDR_FILEVIEW_PROJECT            146
#define IDR_FILEVIEW_FILE               147
#define IDR_FILEVIEW_FOLDER             148
#define IDR_POPUP_ITEM                  153
#define STE_TEX_FILES                   155
#define STE_TCP_INVALID                 171
#define STE_XML_PARSE_ERROR             172
#define IDS_NEWTEXTMODULE               174
#define STE_XML_INSTALLNEEDED           175
#define ID_START_SEARCH                 190
#define IDR_OUTPUT                      191
#define ID_METAPOST_NEW                 192
#define ID_BIBTEX_NEW                   193
#define IDR_LATEX                       194
#define IDR_FIND                        199
#define IDR_IMAGES                      201
#define IDR_HIDDEN_CMDS                 206
#define IDR_POPUP_REGULAREXPRESSION     213
#define IDB_NAVIGATION_BAR              214
#define IDR_POPUP_PLACEHOLDER           217
#define IDB_ITEM_TYPES                  218
#define IDR_ADDITIONAL_COMMANDS         219
#define IDB_OUTPUT_BAR                  220
#define IDR_ERROR_LIST                  221
#define IDR_MDI_CLIENT                  226
#define IDR_POPUP_PLACEHOLDER_DIR       227
#define IDB_FILE_VIEW                   229
#define IDR_POPUP_MDICLIENT             231
#define IDR_POPUP_PLACEHOLDEREX_OPT     233
#define IDB_TEXNICCENTER                236
#define IDR_POPUP_PLACEHOLDER_OPT       239
#define IDB_PARSE_VIEW                  243
#define IDR_POPUP_PLACEHOLDER_MAIN_OPT  246
#define IDR_POPUP_PLACEHOLDER_CURRENT_OPT 247
#define IDR_LATEXTYPE_YELLOW            248
#define IDR_MAINFRAME_YELLOW            250
#define IDR_LATEXWIZARD_YELLOW          251
#define IDS_SPELL_CONTINUE              252
#define IDR_POPUP_PLACEHOLDEREX_NOOPT   253
#define IDS_NO_ACTION                   255
#define IDR_FORMAT                      269
#define IDS_TEXTMODULES_NONEDEFINED     271
#define IDR_STRUCTURE                   280
#define STE_TB_MATH                     309
#define IDR_MATH                    310
#define IDR_MATHBAR1                    311
#define IDR_MATHBAR2                    312
#define IDR_MATHBAR3                    313
#define IDR_MATHBAR4                    314
#define IDR_MATHBAR5                    315
#define IDR_MATHBAR6                    316
#define IDR_MATHBAR7                    317
#define IDR_MATHBAR8                    318
#define IDR_MATHBAR9                    319
#define IDR_MATHBAR10                   320
#define IDR_MATHBAR11                   321
#define IDR_MATHBAR12                   322
#define IDR_MATHBAR13                   323
#define IDR_MATHBAR14                   324
#define IDR_MATHBAR15                   325
#define IDR_MATHBAR16                   326
#define IDR_POPUP_ATTRIBUTE             333
#define IDS_DO_SAVE                     345
#define IDR_BIB_SEARCH                  346
#define IDR_BIB_SEARCH_OPTIONS          348
#define IDB_WIZARD                      349
#define STE_TOOL_NOCMDLINE              464
#define IDS_LANGUAGE                    483
#define IDS_DIALECT                     484
#define ID_SPELL_ERROR_FIRST            700
#define ID_SPELL_ERROR_LAST             799
#define ID_WINDOW_FIRST                 800
#define ID_WINDOW_LAST                  849
#define IDR_USER_TOOLBAR_FIRST          900
#define IDR_USER_TOOLBAR_LAST           999
#define IDD_ABOUTBOX                    1000
#define IDC_TREE                        1001
#define IDD_ABOUTBOX1                   1002
#define IDD_ACTIVE_COMPILER_TYPE        1003
#define IDD_ACTIVE_PROFILE              1004
#define IDD_AUTOCOMPLETE                1005
#define IDD_COMPILER_TYPE               1006
#define IDD_CUSTOMIZE_TOOLS_ADV         1007
#define IDD_CUSTOMIZEPAGE_EDITOR        1008
#define IDD_DIALOG1                     1009
#define IDD_DOCUMENT_NEW                1010
#define IDD_FILE_NEW                    1011
#define IDD_FILE_SAVE                   1012
#define IDD_FILE_TEMPLATE               1013
#define IDD_FILECLEANCONFIRM            1014
#define IDC_TAB_CATEGORIES              1015
#define IDD_FILESEARCH                  1016
#define IDC_PROJECT_NAME                1017
#define IDC_PATH                        1018
#define IDD_FLOATOBJECT                 1019
#define IDC_NEW_MAIN                    1020
#define IDC_EXISTING_MAIN               1021
#define IDD_GET_PATH                    1022
#define IDD_GOTO                        1023
#define IDC_TEMPLATES                   1024
#define IDD_GRAPHIC                     1025
#define IDC_REMOVE_TEMPLATES            1026
#define IDC_DOCUMENTTEMPLATES           1027
#define IDD_HEADER                      1028
#define IDD_ITEM_PROPERTIES             1029
#define IDD_OPTIONS_EDITOR              1030
#define IDD_OPTIONS_FILE                1031
#define IDD_OPTIONS_FILECLEAN           1032
#define IDD_OPTIONS_FILECLEAN1          1033
#define IDC_OUTTYPE_EXT                 1034
#define IDC_VIEWER_START                1035
#define IDC_VIEWER_STARTEX              1036
#define IDC_OUTPUTTYPES                 1037
#define IDC_PROJECT_PATH                1038
#define IDD_OPTIONS_GENERIC             1039
#define IDC_DIR                         1040
#define IDD_OPTIONS_LATEX               1041
#define IDC_MAIN_FILE                   1042
#define IDD_OPTIONS_PATHS               1043
#define IDD_OPTIONS_SPELLING            1044
#define IDD_OPTIONS_TEXTFORMAT          1045
#define IDC_CAPTION                     1046
#define IDD_OUTPUTWIZARD_DVIVIEWER      1047
#define IDD_OUTPUTWIZARD_FINISH         1048
#define IDC_FLOAT_POSBOTTOM             1049
#define IDC_FLOAT_POSPAGE               1050
#define IDC_FLOAT_POSONECOL             1051
#define IDC_FLOAT_POSTWOCOL             1052
#define IDD_OUTPUTWIZARD_MIKTEX         1053
#define IDD_OUTPUTWIZARD_PATH           1054
#define IDC_FLOAT_LABEL                 1055
#define IDC_FLOAT_CAPTION               1056
#define IDC_GRAPHIC_FILE                1057
#define IDC_GRAPHIC_BROWSE              1058
#define IDC_GRAPHIC_SCALE               1059
#define IDC_SPIN_SCALE                  1060
#define IDD_OUTPUTWIZARD_PDFVIEWER      1061
#define IDD_OUTPUTWIZARD_PSVIEWER       1062
#define IDD_OUTPUTWIZARD_WELCOME        1063
#define IDD_OUTSOURCE                   1064
#define IDD_PACKAGE_SCAN_PROGRESS       1065
#define IDD_PLACEHOLDER_SET             1066
#define IDD_PLACEHOLDER_SINGLE          1067
#define IDD_PROFILE                     1068
#define IDC_GRAPHIC_FLOAT               1069
#define IDC_GRAPHIC_BSCALE              1070
#define IDD_PROFILE_EXCHANGE            1071
#define IDC_GRAPHIC_CENTER              1072
#define IDC_TABULAR_CENTER              1073
#define IDC_TABULAR_FLOAT               1074
#define IDC_TABULAR_VTOP                1075
#define IDC_TABULAR_VCENTER             1076
#define IDC_TABULAR_VBOTTOM             1077
#define IDD_PROFILE_LATEX               1078
#define IDC_GROUPPOS                    1079
#define IDC_GROUPWIDTH                  1080
#define IDC_LABELCAPTION                1081
#define IDC_LABELLABEL                  1082
#define IDC_LABELSCALE                  1083
#define IDC_OPTIONS_RESTORE_SESSION     1084
#define IDC_OPTIONS_SAVE_BEFORE_COMPILATION 1085
#define IDC_OPTIONS_SAVE_AUTOMATIC      1086
#define IDC_OPTIONS_SAVE_INTERVALL_EDIT 1087
#define IDD_PROFILE_NAME                1088
#define IDC_OPTIONS_SAVE_INTERVALL_SPIN 1089
#define IDC_OPTIONS_SAVE_LABEL1         1090
#define IDC_OPTIONS_SAVE_LABEL2         1091
#define IDC_OPTIONS_REPLACE_QM          1092
#define IDC_OPTIONS_QM_LABEL1           1093
#define IDC_OPTIONS_QM_LABEL2           1094
#define IDC_OPTIONS_REPLACE_QM_OPEN_EDIT 1095
#define IDC_OPTIONS_REPLACE_QM_CLOSE_EDIT 1096
#define IDC_WINDOW_LIST                 1097
#define IDC_WINDOW_ACTIVATE             1098
#define IDC_WINDOW_SAVE                 1099
#define IDC_WINDOW_CLOSE                1100
#define IDC_GOTO_LINE_EDIT              1101
#define IDC_GOTO_LINE_SPIN              1102
#define IDD_PROFILE_POSTPROCESSOR       1103
#define IDD_PROFILE_VIEWER              1104
#define IDD_PROJECT_NEW                 1105
#define IDD_PROJECT_PROPERTIES          1106
#define IDD_SCINTILLA_FINDDLGORD        1107
#define IDD_SCINTILLA_REPLACEDLGORD     1108
#define IDD_SPELL_CHECK                 1109
#define IDD_TABULAR                     1110
#define IDC_URL_TEXNICCENTER            1111
#define IDD_TEXTMODULES                 1112
#define IDC_URL_TEXNICCENTER2           1113
#define IDD_TIP                         1114
#define IDD_TRANSPARENCY                1115
#define IDC_FILE_FORMAT                 1116
#define IDD_WINDOW                      1117
#define IDC_OUTSOURCE_OPEN_FOREGROUND   1118
#define IDC_TYPE_DOS                    1119
#define IDC_TYPE_UNIX                   1120
#define IDC_TYPE_MAC               1122
#define IDC_SEARCH_SEARCHFOR            1123
#define IDC_POPUP_REGULAREXPRESSION     1124
#define IDC_SEARCH_SEARCHTHROUGH        1125
#define IDC_SEARCH_SEARCHIN             1126
#define IDB_BITMAP1                     1127
#define IDC_SEARCH_WHOLEWORDS           1128
#define IDC_SEARCH_CASESENSITIVE        1129
#define IDC_SEARCH_REGULAREXPRESSION    1130
#define IDC_SEARCH_INCLUDESUBFOLDERS    1131
#define IDC_SEARCH_OUTPUT1              1132
#define IDC_SEARCH_OUTPUT2              1133
#define IDB_BITMAP2                     1134
#define IDB_BITMAP3                     1135
#define IDB_BITMAP4                     1136
#define IDB_BUILD_ANIMATION             1137
#define IDS_UNNAMED_BOOKMARK_FORMAT     1138
#define IDR_MENU1                       1139
#define STE_ALL_FILES_FILTER            1140
#define IDC_OW_MIKTEXYES                1141
#define IDC_OW_MIKTEXNO                 1142
#define IDC_OW_PATH                     1143
#define IDC_OW_BROWSEPATH               1144
#define STE_APPENDIX                    1145
#define STE_BIB_FILES                   1146
#define STE_BIBTEX_ERR_COUNT            1147
#define STE_BIBTEX_ERR_DUP_KEY          1148
#define STE_BIBTEX_ERR_INVALID_EOF      1149
#define IDC_OW_VIEWERPATH               1150
#define IDC_OW_VIEWERBROWSE             1151
#define IDC_OW_VIEWERSI                 1152
#define IDC_OW_VIEWERFWSEARCH           1153
#define IDC_OW_VIEWERPOPUP              1154
#define IDC_OW_OPTLIST                  1155
#define IDC_TAB_PROFILEPAGES            1156
#define STE_BIBTEX_ERR_INVALID_TYPE     1157
#define STE_BIBTEX_ERR_MISSING_KEY      1158
#define IDC_BROWSE_VIEWERPATH           1159
#define STE_BIBTEX_ERR_QOUTEWITHINQUOTE 1160
#define STE_BIBTEX_ERR_SUSPICOUS_LINE   1161
#define IDC_VIEW_CMDTYPE                1162
#define IDC_VIEW_CMDTYPE1               1163
#define STE_BIBTEX_ERR_WRONGLEVELAT     1164
#define STE_COLOR_AUTOMATIC             1165
#define STE_COLOR_OTHERS                1166
#define IDC_VIEWEX_CMDTYPE              1167
#define IDC_VIEWEX_CMDTYPE1             1168
#define STE_COMPILER_DELETE             1169
#define STE_COMPILER_DELETE_EX          1170
#define IDC_TITLE_VIEWEXDDETOPIC        1171
#define IDC_TITLE_VIEWDDETOPIC          1172
#define STE_COMPILER_FILTER             1173
#define IDC_CLOSE_CMDTYPE               1174
#define IDC_CLOSE_CMDTYPE1              1175
#define STE_COMPILER_LATEX_TYPE         1176
#define IDC_TITLE_CLOSEDDETOPIC         1177
#define STE_COMPILER_LATEX_TYPE_EXT     1178
#define IDC_CLOSE_CMDTYPE2              1179
#define IDC_VIEWCMD_PLACEHOLDER         1180
#define IDC_TITLE_VIEWCMD               1181
#define STE_COMPILER_SET_COMPILER       1182
#define STE_COMPILER_SET_INTYPE         1183
#define STE_COMPILER_SET_OUTDESCR       1184
#define STE_COMPILER_SET_OUTEXT         1185
#define STE_CURRENTDOC_DESCRIPTION      1186
#define STE_CUSTOM                      1187
#define STE_CUSTOMIZE_TOOLS_ADVBTN      1188
#define STE_DICTIONARY_CREATE_FAIL      1189
#define STE_DICTIONARY_OPEN_FAIL        1190
#define STE_DOCUMENT_ALREADYEXISTS      1191
#define STE_DOCUMENT_CANNOTCREATE       1192
#define STE_DOCUMENT_SAVEBEFOREPROCEED  1193
#define STE_DOCUMENTDIR_CREATE_ERR      1194
#define STE_EMPTYDOCUMENT_CATEGORY      1195
#define STE_EMPTYDOCUMENT_DESCRIPTION   1196
#define STE_EMPTYDOCUMENT_TITLE         1197
#define STE_EMPTYPROJECT_CATEGORY       1198
#define STE_EMPTYPROJECT_DESCRIPTION    1199
#define STE_EMPTYPROJECT_TITLE          1200
#define STE_ENTRIES_COUNT               1201
#define STE_FILE_DICFILTER              1202
#define STE_FILE_EXEFILTER              1203
#define STE_FILE_EXIST                  1204
#define STE_FILE_EXTERNALCHANGE         1205
#define STE_FILE_EXTERNALCHANGEEX       1206
#define STE_FILE_INUSE                  1207
#define STE_FILE_INUSE_OPEN             1208
#define STE_FILE_LATEXFILTER            1209
#define STE_FILE_MRU_FILE_NONE          1210
#define STE_FILE_MRU_PROJECT_NONE       1211
#define STE_FILE_XMLFILTER              1212
#define STE_FILECLEAN_ERROR             1213
#define STE_FILECLEAN_HCLEAN            1214
#define STE_FILECLEAN_HEAD1             1215
#define STE_FILECLEAN_HEAD2             1216
#define STE_FILECLEAN_HEAD3             1217
#define STE_FILECLEAN_HEAD4             1218
#define STE_FILECLEAN_HNONE             1219
#define STE_FILECLEAN_HPROTECT          1220
#define STE_FILECLEAN_HPROTECTBYDEFAULT 1221
#define STE_FILECLEAN_INVALIDPATTERN    1222
#define STE_FILECLEAN_NOTRECURSIVE      1223
#define STE_FILECLEAN_RECURSIVE         1224
#define STE_FILEFIND_BROWSEDIR          1225
#define STE_FILEFIND_INVALIDEXPRESSION  1226
#define STE_FLOATPREFIX_FIGURE          1227
#define STE_FLOATPREFIX_TABLE           1228
#define STE_FLOATTITLE_INSERT_FIGURE    1229
#define STE_FLOATTITLE_INSERT_TABLE     1230
#define STE_FLOATTYPE_FIGURE            1231
#define STE_FLOATTYPE_TABLE             1232
#define STE_GET_PATH                    1233
#define STE_GET_PATH_TITLE              1234
#define STE_GRAPHIC_FILES               1235
#define STE_GRAPHICS_FILES              1236
#define STE_GREP_CANCELED               1237
#define STE_GREP_ERROR                  1238
#define STE_GREP_FAILED                 1239
#define STE_GREP_FINISHED               1240
#define STE_GREP_FINISHEDNOHIT          1241
#define STE_GREP_HIT                    1242
#define STE_GREP_START                  1243
#define STE_HEADER_CHAPTER              1244
#define STE_HEADER_PARAGRAPH            1245
#define STE_HEADER_PART                 1246
#define STE_HEADER_SECTION              1247
#define STE_HEADER_SUBPARAGRAPH         1248
#define STE_HEADER_SUBSECTION           1249
#define STE_HEADER_SUBSUBSECTION        1250
#define STE_HEADERPREFIX_CHAPTER        1251
#define STE_HEADERPREFIX_PARAGRAPH      1252
#define STE_HEADERPREFIX_PART           1253
#define STE_HEADERPREFIX_SECTION        1254
#define STE_HEADERPREFIX_SUBPARAGRAPH   1255
#define STE_HEADERPREFIX_SUBSECTION     1256
#define STE_HEADERPREFIX_SUBSUBSECTION  1257
#define STE_ITEMTYPE_CENTER             1258
#define STE_ITEMTYPE_DESCRIPTION        1259
#define STE_ITEMTYPE_ENUMERATION        1260
#define STE_ITEMTYPE_EQUATION           1261
#define STE_ITEMTYPE_FIGURE             1262
#define STE_ITEMTYPE_GENERIC            1263
#define STE_ITEMTYPE_HEADER             1264
#define STE_ITEMTYPE_ITEMIZATION        1265
#define STE_ITEMTYPE_QUOTATION          1266
#define STE_ITEMTYPE_QUOTE              1267
#define STE_ITEMTYPE_TABLE              1268
#define STE_ITEMTYPE_UNKNOWNENV         1269
#define STE_ITEMTYPE_VERSE              1270
#define STE_LANGUAGE_ENGLISH            1271
#define STE_LANGUAGE_FRENCH             1272
#define STE_LANGUAGE_GERMAN             1273
#define STE_LANGUAGE_NEW                1274
#define STE_LATEX_CANCELED              1275
#define STE_LATEX_CITE                  1276
#define STE_LATEX_EQREF                 1277
#define STE_LATEX_PAGEREF               1278
#define STE_LATEX_REF                   1279
#define STE_LATEX_RESULT                1280
#define STE_LATEX_START                 1281
#define STE_LATEX_START_FAILED          1282
#define STE_LATEX_START_FAILED_EXT      1283
#define STE_LICENSE_FILE                1284
#define STE_MAINFILE_DESCRIPTION        1285
#define STE_NAVIGATIONBAR_TITLE         1286
#define STE_NOFOLDER                    1287
#define STE_OPTIONS_REQUIRES_RESTART    1288
#define STE_OPTIONS_TITLE               1289
#define STE_OUTPUT_TITLE                1290
#define STE_OUTPUTWIZARD_DVIPDFMTYPE    1291
#define STE_OUTPUTWIZARD_DVITYPE        1292
#define STE_OUTPUTWIZARD_NOLATEX        1293
#define STE_OUTPUTWIZARD_OUTPUTTYPEEXISTS 1294
#define STE_OUTPUTWIZARD_PDFTYPE        1295
#define STE_OUTPUTWIZARD_PDFVIAPSTYPE   1296
#define STE_OUTPUTWIZARD_PSTYPE         1297
#define STE_OUTPUTWIZARD_YAPCONFIG      1298
#define STE_PARSE_BEGIN                 1299
#define STE_PARSE_END                   1300
#define STE_PARSE_FOUND                 1301
#define STE_PARSE_FOUND_UNMATCHED       1302
#define STE_PARSE_PARSING               1303
#define STE_PARSE_RESULTS               1304
#define STE_PARSE_TERMINATE             1305
#define STE_PDICT_OPEN_ERROR            1306
#define STE_PHSDLG_NOEXAMPLE            1307
#define STE_PLACEHOLDER_EXAMPLE_CURRENT 1308
#define STE_PLACEHOLDER_EXAMPLE_CURRENT_SHORT 1309
#define STE_PLACEHOLDER_EXAMPLE_MAIN    1310
#define STE_PLACEHOLDER_EXAMPLE_MAIN_SHORT 1311
#define STE_PLACEHOLDERSETS_APF         1312
#define STE_PLACEHOLDERSETS_COF         1313
#define STE_POPUP_EDITOR                1314
#define STE_POPUP_ITEM                  1315
#define STE_POPUP_MAINWINDOWAREA        1316
#define STE_PROFILE_ALREADYEXISTS       1317
#define STE_PROFILE_FILE_FILTER         1318
#define STE_PROFILE_REMOVE              1319
#define STE_PROFILE_UNCOMPLETE          1320
#define STE_PROJECT_CANNOTCREATEMAINFILE 1321
#define STE_PROJECT_CLOSE_ASK           1322
#define STE_PROJECT_EXISTS              1323
#define STE_PROJECT_MAINFILEEXISTS      1324
#define STE_PROJECT_MAINFILENOTFOUND    1325
#define STE_PROJECT_USEEXISTINGFILE     1326
#define STE_PROJECTDIR_CREATE_ERR       1327
#define STE_RESOURCE_CONFLICT           1328
#define STE_SELECT_PROJECT_PATH         1329
#define STE_SESSION_RESTORE_NOTALLWINDOWSRESTORED 1330
#define STE_TAB_BIBENTRIES              1331
#define STE_TAB_BUILD                   1332
#define STE_TAB_ENVIRONMENTS            1333
#define STE_TAB_FILES                   1334
#define STE_TAB_GREP_1                  1335
#define STE_TAB_GREP_2                  1336
#define STE_TAB_PARSE                   1337
#define STE_TAB_STRUCTURE               1338
#define STE_TB_FIND                     1339
#define STE_TB_FORMAT                   1340
#define STE_TB_FORMAT_RECENTLY_USED     1341
#define STE_TB_INSERT                   1342
#define STE_TB_LATEX                    1343
#define STE_TB_MAINFRAME                1344
#define IDS_LINE_NUMBER                 1345
#define IDS_EDIT_TEXT_NOT_FOUND         1346
#define IDS_DO_NOT_SAVE                 1347
#define IDS_BIBTEX_RESULT               1348
#define IDS_SAVE_PACKAGE_AS             1349
#define IDS_SELECT_PACKAGE_DIR          1350
#define IDS_TOOLBAR_CUSTOMIZE           1351
#define IDS_ERROR_LIST                  1352
#define IDS_LOADING                     1353
#define IDS_FORMAT                      1354
#define IDS_ERROR_LIST_ERRORS           1355
#define IDS_ERROR_LIST_WARNINGS         1356
#define IDS_ERROR_LIST_BAD_BOXES        1357
#define IDS_LINE                        1358
#define IDS_DESCRIPTION                 1359
#define IDS_FILE                        1360
#define IDS_ENCODING                    1361
#define IDS_ENCODING_WITH_BOM           1362
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 1363
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 1364
#define IDS_NO_LABEL_AVAILABLE          1365
#define IDS_DEFINE_COLOR_NAME_PLACEHOLDER 1366
#define IDS_MORE_COLORS                 1367
#define IDS_AUTOMATIC                   1368
#define IDS_TEXT_COLORS                 1369
#define IDS_BACKGROUND_COLORS           1370
#define IDS_SEARCH                      1371
#define IDS_LABEL                       1372
#define IDS_AUTHOR                      1373
#define IDS_TITLE                       1374
#define IDS_YEAR                        1375
#define IDS_PUBLICATION_TYPE            1376
#define IDS_PUBLISHER                   1377
#define IDS_WELCOME_WIZARD              1378
#define IDS_WIZARD_MIKTEX_DETECTED      1379
#define IDC_STATIC_BACKGROUND           1380
#define IDC_VERSION                     1381
#define IDC_URL                         1382
#define IDC_CREDITS                     1383
#define IDC_LOGO                        1384
#define IDS_WIZARD_CONFIGURE_PDF        1385
#define IDS_WIZARD_FINALIZE             1386
#define IDS_WIZARD_WELCOME              1387
#define IDS_WIZARD_CONFIGURE_PS         1388
#define IDS_WIZARD_CONFIGURE_DVI        1389
#define IDS_WIZARD_DISTRIBUTION_PATH    1390
#define IDS_SEARCHING                   1391
#define IDS_ITEMS_FOUND                 1392
#define IDS_CONFIGURE_FOUND_DISTRIBUTION 1393
#define IDS_RECURSIVE_INCLUSION         1394
#define IDC_EDIT_BIBTEXARGUMENTS        1500
#define IDC_EDIT_BIBTEXPATH             1501
#define IDR_LATEXDOCTYPE                1502
#define IDR_BIBTEXDOCTYPE               1503
#define IDR_METAPOSTDOCTYPE             1504
#define IDR_LATEXPROJECTDOCTYPE         1505
#define IDB_DOCUMENTTYPES               1506
#define IDS_BIBLIOGRAPHY                1507
#define IDC_EDIT_CLOSECMD               1508
#define IDS_BOOKMARK                    1509
#define IDR_LATEXWIZARD                 1510
#define IDS_FILE_LOCATION               1511
#define IDC_EDIT_CLOSEDDESERVER         1513
#define IDC_EDIT_CLOSEDDETOPIC          1514
#define IDC_EDIT_LATEXARGUMENTS         1515
#define IDC_EDIT_LATEXPATH              1516
#define IDC_EDIT_MAKEINDEXARGUMENTS     1517
#define IDC_EDIT_MAKEINDEXPATH          1518
#define IDC_EDIT_MATCH_CASE             1519
#define IDC_EDIT_NAME                   1520
#define IDC_EDIT_PPARGUMENTS            1521
#define IDC_EDIT_PPEXE                  1522
#define IDC_EDIT_PPINPUT                1523
#define IDC_EDIT_PPOUTPUT               1524
#define IDC_EDIT_PROJECTNAME            1525
#define IDC_EDIT_PROJECTPATH            1526
#define IDC_EDIT_REPLACE                1527
#define IDC_EDIT_REPLACE_ALL            1528
#define IDC_EDIT_REPLACE_WITH           1529
#define IDC_EDIT_SCOPE_SELECTION        1530
#define IDC_EDIT_SCOPE_WHOLE_FILE       1531
#define IDC_EDIT_SKIP                   1532
#define IDC_EDIT_TEXT                   1533
#define IDC_EDIT_TYPE                   1534
#define IDC_EDIT_VIEWCMD                1535
#define IDC_EDIT_VIEWDDESERVER          1536
#define IDC_EDIT_VIEWDDETOPIC           1537
#define IDC_EDIT_VIEWERPATH             1538
#define IDC_EDIT_VIEWEXCMD              1539
#define IDC_EDIT_VIEWEXDDESERVER        1540
#define IDC_EDIT_VIEWEXDDETOPIC         1541
#define IDC_EDIT_WHOLE_WORD             1542
#define IDC_EDITOR_ELEMENT              1543
#define IDC_EDITOR_ELEMENTCOLOR         1544
#define IDC_EDITOR_FONT                 1545
#define IDC_EDITOR_SELECTFONT           1546
#define IDC_EDITOR_TABWIDTH             1547
#define IDC_OPTIONS_FILECLEAN_DELETE    2048
#define IDC_SEARCH_BROWSE_SEARCHIN      2049
#define IDC_OPTIONS_DEFAULT_PATH_EDIT   2051
#define IDC_OPTIONS_SAVE_NEWDOCS        2052
#define IDC_ADVTOOLS_USEOUTPUT          2053
#define IDC_GUI_LANGUAGE_COMBO          2054
#define IDC_BUTTON_SELECT_NONE          2055
#define IDC_RADIO_VIEW_TYPE             2056
#define IDC_LOOKNFEEL_COMBO             2057
#define IDC_BUTTON_SELECT_ALL           2058
#define IDC_OVERWRITECURSOR_STYLE       2059
#define IDC_OPTIONS_OPTIMIZE_FOR_VISUALLY_HANDICAPPED_USERS 2060
#define IDC_TEXTMODULES_MODULES         2061
#define IDC_PROFILE_EXPORT              2062
#define IDC_PROFILE_LIST                2063
#define IDC_REGULAR_EXPRESSION          2064
#define IDC_RADIO_VIEW_TYPE1            2065
#define IDC_OUTSOURCE_OPEN_BACKGROUND   2066
#define IDC_SELECT_ENCODING             2067
#define IDC_LIST_TEMPLATES              2068
#define IDC_TEMPLATE_LIST               2069
#define IDC_STATIC_NOTE                 2070
#define IDC_ADD_DOCUMENTTEMPLATES       2071
#define IDC_REMOVE_TYPE                 2072
#define IDC_REMOVE_DOCUMENTTEMPLATES    2073
#define IDC_TYPES                       2074
#define IDC_INTYPE_DESCR                2075
#define IDC_OUTPUT_WIZARD               2077
#define IDC_OUTTYPE_DESCR               2078
#define IDC_TITLE                       2079
#define IDC_BROWSE_MAIN_FILE            2080
#define IDC_DEPTH                       2081
#define IDC_FILE                        2082
#define IDC_COMMANDS                    2083
#define IDC_LINE                        2084
#define IDC_LABEL                       2085
#define IDC_FLOAT_POSHERE               2086
#define IDC_FLOAT_POSTOP                2087
#define IDC_COMMENT                     2088
#define IDC_INCREMENTAL_SEARCH          2089
#define IDC_REVERSE_INCREMENTAL_SEARCH  2090
#define IDC_SDRAGCOPY                   2091
#define IDC_SINGLEDRAG                  2092
#define IDC_STATIC1                     2093
#define IDC_POSTPROCESSORLIST           2094
#define IDC_VIEWEXCMD_PLACEHOLDER       2095
#define IDC_TITLE_VIEWEXCMD             2097
#define IDC_BROWSE_POSTPROCESSOR        2098
#define IDC_CLOSECMD_PLACEHOLDER        2099
#define IDC_TITLE_CLOSECMD              2101
#define IDC_TITLE_CLOSEDDESERVER        2102
#define IDC_USELATEX                    2105
#define IDC_INSERTPH_PPARGUMENTS        2106
#define IDC_TITLE_LATEXPATH             2107
#define IDC_INSERTPH_PPINPUT            2108
#define IDC_INSERTPH_PPOUTPUT           2110
#define IDC_BROWSELATEX                 2111
#define IDC_TITLE_LATEXARGUMENTS        2112
#define IDC_LATEXPH                     2114
#define IDC_BROWSEBIBTEX                2116
#define IDC_TITLE_EXE                   2117
#define IDC_TITLE_BIBTEXARGUMENTS       2118
#define IDC_TITLE_ARGUMENTS             2119
#define IDC_TITLE_INPUT                 2121
#define IDC_BIBTEXPH                    2122
#define IDC_TITLE_OUTPUT                2123
#define IDC_BROWSEMAKEINDEX             2125
#define IDC_TITLE_VIEWDDESERVER         2126
#define IDC_TITLE_MAKEINDEXARGUMENTS    2127
#define IDC_TITLE_VIEWEXDDESERVER       2130
#define IDC_MAKEINDEXPH                 2131
#define IDC_PROFILE_ADD                 2134
#define IDC_PROFILE_REMOVE              2135
#define IDC_PROFILE_RENAME              2136
#define IDC_PROFILE_COPY                2137
#define IDC_LIST_PROFILES               2139
#define IDC_PROFILES                    2140
#define IDC_CHECK_BIBTEX                2141
#define IDC_CHECK_MAKEINDEX             2142
#define IDC_DONTUSEBIBTEX               2143
#define IDC_TITLE_BIBTEXPATH            2144
#define IDC_DONTUSEMAKEINDEX            2145
#define IDC_TITLE_MAKEINDEXPATH         2147
#define IDC_BUTTON_BROWSE               2149
#define IDC_STATIC_DESCRIPTION          2150
#define IDC_BUTTON_CREATE               2151
#define IDC_OPTIONS_FILETYPE            2154
#define IDC_STATIC_FORMATTITLE          2155
#define IDC_STATIC_ENCODING             2156
#define IDC_PROFILE_WIZARD              2158
#define IDC_EMPTYMESSAGE                2159
#define IDC_WINDOW                      2160
#define IDC_PROJECTTEMPLATES            2162
#define IDC_ADD_PROJECTTEMPLATES        2163
#define IDC_REMOVE_PROJECTTEMPLATES     2164
#define IDC_STOPONLATEXERROR            2165
#define IDC_OPTIONS_LANGUAGE            2166
#define IDC_OPTIONS_SPELL_ENABLE        2167
#define IDC_OPTIONS_LANGUAGE_DIALECT    2168
#define IDC_OPTIONS_SPELL_COMMENT       2169
#define IDC_OPTIONS_SPELL_SKIP_TAGS     2170
#define IDC_OPTIONS_SPELL_IGNORE_NUM    2171
#define IDC_OPTIONS_SPELL_MAINDICT      2172
#define IDC_OPTIONS_SPELL_IGNORE_ALLCAPS 2173
#define IDC_OPTIONS_SPELL_PDICT         2174
#define IDC_OPTIONS_SPELL_BROWSE        2175
#define IDC_FCCONFIRM_CLEANEDFILES      2176
#define IDC_FCCONFIRM_PROTECTEDFILES    2177
#define IDC_FCCONFIRM_LABELPROTECTED    2178
#define IDC_FCCONFIRM_LABELCLEAN        2179
#define IDC_FCCONFIRM_SHOWDIALOG        2180
#define IDC_OPTIONS_FILECLEAN_CONFIRM   2181
#define IDC_OPTIONS_FILECLEAN_LIST      2182
#define IDC_OPTIONS_FILECLEAN_NAME      2183
#define IDC_OPTIONS_FILECLEAN_PATTERN   2184
#define IDC_OPTIONS_FILECLEAN_HANDLING  2185
#define IDC_OPTIONS_FILECLEAN_RECURSIVE 2186
#define IDC_OPTIONS_FILECLEAN_PHINSERT  2187
#define IDC_OPTIONS_FILECLEAN_NEW       2188
#define IDC_BROWSE_DEFAULT_PATH         2189
#define IDC_PLACEHOLDER_SINGLE_SHORT    2190
#define IDC_PLACEHOLDER_SINGLE_FORWARD  2191
#define IDC_PLACEHOLDER_SINGLE_EXAMPLE  2192
#define IDC_PLACEHOLDER_SINGLE_PHTYPE   2193
#define IDC_PLACEHOLDER_SINGLE_WHAT     2194
#define IDC_PLACEHOLDER_SINGLE_RESULT   2195
#define IDC_OPTIONS_LANGUAGE_LOCALE     2196
#define IDC_GRAPHIC_SCALETEXTWIDTH      2197
#define IDC_PLACEHOLDER_SET_EXAMPLE     2198
#define IDC_PLACEHOLDER_SET_RESULT      2199
#define IDC_PLACEHOLDER_SET_PHTYPE      2200
#define IDC_PLACEHOLDER_SET_QUOTED      2201
#define IDC_PLACEHOLDER_SET_RELATIVE    2202
#define IDC_PLACEHOLDER_SET_SHORT       2203
#define IDC_PLACEHOLDER_SET_FORWARD     2204
#define IDC_ADVTOOLS_PROMPTARG          2205
#define IDC_ADVTOOLS_CLOSEWIN           2206
#define IDC_OPTIONS_LANGUAGE_DOWNLOAD   2207
#define IDC_INSERCURSOR_STYLE           2208
#define IDC_INSERTCURSOR_BLINK          2209
#define IDC_OVERWRITECURSOR_BLINK       2210
#define IDC_TEXTMODULES_NEWMODULE       2211
#define IDC_TEXTMODULES_DELETEMODULE    2212
#define IDC_TEXTMODULES_MENUBTN         2213
#define IDC_TEXTMODULES_NAME            2214
#define IDC_TEXTMODULES_BEFORECURSOR    2215
#define IDC_TEXTMODULES_AFTERCURSOR     2216
#define IDC_TEXTMODULES_PARAMSENABLE    2217
#define IDC_TEXTMODULES_PARAMSGROUP     2218
#define IDC_PROFILE_IMPORT              2219
#define IDC_REMOVE_DIRECTORY_SPECIFICATIONS 2220
#define IDC_STATIC_EXPORT               2221
#define IDC_STATIC_IMPORT               2222
#define IDC_BUTTON_SELECT_INVERT        2223
#define IDC_OPTIONS_REPLACE_QM_PREDEFINED_COMBO 2224
#define IDC_OPTIONS_QM_SET_LABEL        2225
#define IDC_CANCEL                      2226
#define IDC_SHOW_LINENUMBERS            2227
#define IDC_LIST                        2228
#define IDC_OPTIONS_EDITOR_WORDWRAP_STYLE 2229
#define IDC_OPTIONS_EDITOR_WORDWRAP_FIXEDCOLUMN 2230
#define IDC_OUTSOURCE_FILENAME          2231
#define IDC_OUTSOURCE_BROWSEBUTTON      2232
#define IDC_OUTSOURCE_DIRECTORY         2233
#define IDC_OUTSOURCE_CMDLEFT           2234
#define IDC_OUTSOURCE_CMDRIGHT          2235
#define IDC_OUTSOURCE_CMDINPUT          2236
#define IDC_OUTSOURCE_CMDINCLUDE        2237
#define IDC_OUTSOURCE_CMDUSERDEF        2238
#define IDC_OUTSOURCE_OPEN              2239
#define IDC_COPYRIGHT                   2240
#define IDC_SHOW_LINE_BELOW_FOLD        2241
#define IDC_SHOW_LINE_ABOVE_FOLD        2242
#define IDC_SHOW_LINE_BELOW_NO_FOLD     2243
#define IDC_SHOW_LINE_ABOVE_NO_FOLD     2244
#define IDC_USE_SPACES                  2245
#define IDC_SLIDER1                     2246
#define IDC_SLIDER_VALUE                2247
#define IDC_FOLD_COMPACT                2248
#define IDC_NEXTTIP                     2249
#define IDC_STARTUP                     2250
#define IDC_TIPSTRING                   2251
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDS_EDITOP_FIRSTMODIFY          8630
#define STE_OUTPUTWIZARD_PDFVIAXELATEX  8631
#define IDS_FIND_INCREMENTAL_FORWARD    8640
#define IDS_FIND_INCREMENTAL_BACKWARD   8641
#define IDS_FIND_INCREMENTAL_FAILED     8642
#define IDS_EDIT_REPLACE_COUNT          8643
#define IDS_INCREMENTAL_SEARCH_PASSED_START_SEARCH 8644
#define IDC_SPELL_REPLACE               8650
#define IDC_SPELL_REPLACE_ALL           8651
#define IDC_SPELL_RESUME                8652
#define IDC_SPELL_IGNORE_ALL            8653
#define IDC_SPELL_TEXT                  8654
#define IDC_SPELL_IGNORE                8655
#define IDC_SPELL_NEXT                  8656
#define IDC_SPELL_SUGGEST               8657
#define IDC_SPELL_ADD                   8658
#define IDS_SPELL_IGNORE                8659
#define IDS_SPELL_UNEDIT                8660
#define IDS_SPELL_DONE                  8661
#define IDS_SPELL_NO_SUGGESTIONS        8662
#define IDS_MISSING_SECTION             8663
#define ID_TEXTMODULES_FIRST            17000
#define ID_TEXTMODULES_LAST             18000
#define ID_VIEW_BAR1                    32760
#define ID_VIEW_BAR2                    32761
#define ID_BIB_VIEW                     32769
#define ID_BG_UPDATE_PROJECT            32770
#define ID_TIP                          32771
#define ID_UPDATE_LATEX_OUTPUT          32773
#define ID_NEXT_ERROR                   32774
#define ID_PREV_ERROR                   32775
#define ID_PROJECT_MRU_PROJECT1         32781
#define ID_VIEW_NAVIGATION              32784
#define ID_VIEW_OUTPUT                  32785
#define ID_PROJECT_PROPERTIES           32786
#define ID_NEXT_WARNING                 32795
#define ID_PREV_WARNING                 32796
#define ID_NEXT_BADBOX                  32797
#define ID_PREV_BADBOX                  32798
#define ID_PROJECT_OPEN_MAINFILE        32799
#define ID_PROJECT_PARSED               32800
#define ID_PROJECT_PARSE                32801
#define ID_DOCUMENT_SAVED               32807
#define ID_HELP_CONTENTS                33033
#define ID_HELP_KEYMAPPING              33034
#define ID_IDRPOPUPITEM_GEHEZU          33035
#define ID_OPTIONS_CHANGED              33113
#define ID_WINDOW_LIST                  33114
#define ID_WINDOW_LIST_MENU             33115
#define ID_MATH1                        33194
#define ID_MATH2                        33195
#define ID_MATH3                        33196
#define ID_MATH4                        33197
#define ID_MATH5                        33198
#define ID_MATH6                        33199
#define ID_MATH7                        33200
#define ID_MATH8                        33201
#define ID_MATH9                        33202
#define ID_MATH10                       33203
#define ID_MATH11                       33204
#define ID_MATH12                       33205
#define ID_MATH13                       33206
#define ID_MATH14                       33207
#define ID_MATH15                       33208
#define ID_MATH16                       33209
#define ID_VIEW_MATH                    33221
#define ID_PH_MPATH                     33239
#define ID_PH_MSLASHPATH                33240
#define ID_PH_MBASE                     33241
#define ID_PH_MSLASHBASE                33242
#define ID_PH_MROOT                     33243
#define ID_PH_MDIR                      33244
#define ID_PH_MSLASHDIR                 33245
#define ID_PH_MNAME                     33246
#define ID_PH_MTITLE                    33247
#define ID_PH_MEXTENSION                33248
#define ID_PH_MSPATH                    33249
#define ID_PH_MSSLASHPATH               33250
#define ID_PH_MSBASE                    33251
#define ID_PH_MSSLASHBASE               33252
#define ID_PH_MSDIR                     33253
#define ID_VIEW_INSERT                  33254
#define ID_VIEW_LATEX                   33255
#define ID_VIEW_FORMAT                  33256
#define ID_VIEW_FORMAT_RECENTLY_USED    33257
#define ID_VIEW_MENU_BAR                33258
#define ID_VIEW_FIND                    33259
#define ID_PH_MSSLASHDIR                33260
#define ID_PH_CPATH                     33261
#define ID_PH_CSLASHPATH                33262
#define ID_PH_CBASE                     33263
#define ID_PH_CSLASHBASE                33264
#define ID_PH_CROOT                     33265
#define ID_PH_CDIR                      33266
#define ID_PH_CSLASHDIR                 33267
#define ID_PH_CNAME                     33268
#define ID_PH_CTITLE                    33269
#define ID_WINDOW_EDITOR                33270
#define ID_WINDOW_NAVIGATOR             33271
#define ID_WINDOW_STRUCTURE             33272
#define ID_WINDOW_ENVIRONMENT           33273
#define ID_WINDOW_FILES                 33274
#define ID_PH_CEXTENSION                33275
#define ID_PH_CSPATH                    33276
#define ID_PH_CSSLASHPATH               33277
#define ID_PH_CSBASE                    33278
#define ID_PH_CSSLASHBASE               33279
#define ID_PH_CSDIR                     33280
#define ID_PH_CSSLASHDIR                33281
#define ID_PH_CLINENR                   33282
#define ID_PH_PERCENT                   33283
#define ID_PROJECT_NEW                  33286
#define ID_PROJECT_OPEN                 33287
#define ID_PROJECT_SAVE                 33288
#define ID_PROJECT_CLOSE                33289
#define ID_ITEM_GOTO                    33290
#define ID_ITEM_INSERT_LABEL            33291
#define ID_ITEM_INSERT_PAGEREF          33292
#define ID_ITEM_INSERT_REF              33293
#define ID_ITEM_PROPERTIES              33294
#define ID_PH_CSELECTION                33295
#define ID_LATEX_BIBTEX                 33296
#define ID_SPELL_PROJECT                33299
#define ID_VIEW_USER_TOOLBAR_FIRST      33300
#define ID_SPELL_FILE                   33301
#define ID_PHS_ALLPROJECTFILES          33302
#define ID_PHS_ALLTEXFILES              33303
#define ID_PHS_ALLBIBTEXFILES           33304
#define ID_PHS_ALLGRAPHICFILES          33305
#define ID_PHS_ALLOPENEDFILES           33306
#define ID_PHS_ALLTXCFILES              33307
#define ID_PHS_ALLFILESETS              33308
#define ID_PHS_DOLLAR                   33309
#define ID_LATEX_CLEAN                  33310
#define ID_PH_MAINOPTIONS               33311
#define ID_PH_CURRENTOPTIONS            33312
#define ID_PHS_ALLPROJECTFILES_Q        33313
#define ID_PHS_ALLOPENEDFILES_Q         33314
#define ID_PHS_ALLTEXFILES_Q            33315
#define ID_PHS_ALLBIBTEXFILES_Q         33316
#define ID_PHS_ALLGRAPHICFILES_Q        33317
#define ID_PHS_ALLTXCFILES_Q            33318
#define ID_PHS_ALLFILESETS_Q            33319
#define ID_PHS_ALLPROJECTFILES_QR       33320
#define ID_PHS_ALLOPENEDFILES_QR        33321
#define ID_PHS_ALLTEXFILES_QR           33322
#define ID_PHS_ALLBIBTEXFILES_QR        33323
#define ID_PHS_ALLGRAPHICFILES_QR       33324
#define ID_PHS_ALLTXCFILES_QR           33325
#define ID_PHS_ALLFILESETS_QR           33326
#define ID_PHS_TEST_NOOPT               33327
#define ID_PHS_TEST_OPT                 33328
#define ID_PHS_MORESETS_NOOPT           33329
#define ID_PH_MAINOPTIONS_NOOPT         33330
#define ID_PH_CURRENTOPTIONS_NOOPT      33331
#define ID_PH_MRELATIVEPATH             33332
#define ID_PH_MSLASHRELATIVEPATH        33333
#define ID_PH_MSHORTRELATIVEPATH        33334
#define ID_PH_MSSLASHRELATIVEPATH       33335
#define ID_PH_CRELATIVEPATH             33336
#define ID_PH_CSLASHRELATIVEPATH        33337
#define ID_PH_CSHORTRELATIVEPATH        33338
#define ID_PH_CSSLASHRELATIVEPATH       33339
#define ID_PHS_MORESETS_OPT             33340
#define ID_PROJECT_NEW_FROM_FILE        33341
#define ID_TEXTMODULES_DEFINE           33347
#define ID_VIEW_DOCTAB_TOP              33348
#define ID_VIEW_DOCTAB_BOTTOM           33349
#define ID_VIEW_DOCTAB_OFF              33350
#define ID_VIEW_DOCTAB_ICONS            33351
#define ID_VIEW_DOCTAB_NOTE             33352
#define ID_TOOLS_CANCEL                 33353
#define ID_LATEX_EDITPROFILES           33354
#define ID_LATEX_FILE_NEW               33355
#define ID_PACKAGE_SETUP                33356
#define ID_QUERY_COMPLETION             33357
#define ID_WINDOW_REFERENCES            33358
#define ID_WINDOW_PARSE                 33359
#define ID_WINDOW_CLOSE_ALL_BUTACTIVE   33360
#define ID_WINDOW_CLOSE_SELECTEDTAB     33361
#define ID_VIEW_STRUCT_PANE             33363
#define ID_VIEW_ENV_PANE                33364
#define ID_VIEW_FILES_PANE              33365
#define ID_VIEW_BIB_ENTRIES_PANE        33366
#define ID_VIEW_ERROR_LIST_PANE         33367
#define ID_VIEW_APP_LOOK_WIN_2000       33368
#define ID_VIEW_APP_LOOK_OFFICE_XP      33369
#define ID_VIEW_APP_LOOK_WIN_XP         33370
#define ID_VIEW_APP_LOOK_OFFICE_2003    33371
#define ID_VIEW_APP_LOOK_VS_2005        33372
#define ID_VIEW_APP_LOOK_OFFICE_2007_BLUE 33373
#define ID_VIEW_APP_LOOK_OFFICE_2007_BLACK 33374
#define ID_VIEW_APP_LOOK_OFFICE_2007_SILVER 33375
#define ID_VIEW_APP_LOOK_OFFICE_2007_AQUA 33376
#define ID_SHOW_ERRORS                  33377
#define ID_SHOW_WARNINGS                33378
#define ID_SHOW_BAD_BOXES               33379
#define ID_SHOW_IMAGES                  33380
#define ID_SHOW_EQUATIONS               33381
#define ID_SHOW_TABLES                  33382
#define ID_VIEW_DISPLAYENDLINES         33384
#define ID_VIEW_WORD_WRAP               33385
#define ID_VIEW_TOGGLE_SHOW_LINE_ENDING 33386
#define ID_VIEW_TOGGLE_WORD_WRAP        33387
#define ID_VIEW_TOGGLE_WHITE_SPACE      33388
#define ID_VIEW_LINE_ENDING             33389
#define ID_VIEW_WHITE_SPACE             33390
#define ID_SHOW_LINE_NUMBERS            33391
#define ID_VIEW_LINE_NUMBERS            33392
#define ID_VIEW_DISPLAYLINENUMBERS      33393
#define ID_SEARCH_SPLITPARAGRAPH        33396
#define ID_SEARCH_JOINPARAGRAPH         33397
#define ID_VIEW_SHOW_LINE_ENDING        33398
#define ID_VIEW_USER_TOOLBAR_LAST       33399
#define ID_REGEX_FIRST                  33400
#define ID_REGEX_ANYCHAR                33401
#define ID_REGEX_CHARSET                33402
#define ID_REGEX_NOTCHARSET             33403
#define ID_REGEX_SOL                    33404
#define ID_REGEX_EOL                    33405
#define ID_REGEX_SOW                    33406
#define ID_REGEX_EOW                    33407
#define ID_REGEX_GROUP                  33408
#define ID_REGEX_OR                     33409
#define ID_REGEX_STAR                   33410
#define ID_REGEX_PLUS                   33411
#define ID_REGEX_QM                     33412
#define ID_REGEX_XTIMES                 33413
#define ID_REGEX_XTOYTIMES              33414
#define ID_REGEX_WHITESPACE             33415
#define ID_REGEX_ALNUM                  33416
#define ID_REGEX_ALPHA                  33417
#define ID_REGEX_DECDIGIT               33418
#define ID_REGEX_HEXDIGIT               33419
#define ID_REGEX_WORDCHAR               33420
#define ID_REGEX_UPPERALPHA             33421
#define ID_REGEX_LOWERALPHA             33422
#define ID_SEARCH_OPTIONS               33423
#define ID_SEARCH_EDIT                  33424
#define ID_CLEAR_SEARCH                 33425
#define ID_AUTHOR                       33426
#define ID_YEAR                         33427
#define ID_TITLE                        33428
#define ID_PUBLICATION_TYPE             33429
#define ID_PUBLISHER                    33430
#define ID_VIEW_INDENTATION_GUIDES      33431
#define ID_VIEW_INDENTATIONGUIDES       33432
#define ID_VIEW_TRANSPARENCY            33433
#define ID_NONE                         33434
#define ID_VIEW_BUILD_PANE              33437
#define ID_VIEW_GREP_1_PANE             33438
#define ID_VIEW_GREP_2_PANE             33439
#define ID_VIEW_PARSE_PANE              33440
#define ID_REGEX_LAST                   33499
#define ID_WINDOW_OUTPUT                33500
#define ID_WINDOW_BUILDRESULT           33501
#define ID_WINDOW_GREP1                 33502
#define ID_WINDOW_GREP2                 33503
#define ID_APP_LICENSE                  33507

#define ID_WINDOW_NEXT                  33509
#define ID_WINDOW_PREVIOUS              33510
#define ID_WINDOW_CLOSE_ALL             33511
#define ID_LATEX_FILEBIBTEX             33512
#define ID_LATEX_FILECOMPILE            33513
#define ID_LATEX_FILECOMPILEANDVIEW     33514
#define ID_VIEW_FULLSCREEN              33525
#define ID_LATEX_FILEMAKEINDEX          33553
#define ID_LATEX_MAKEINDEX              33667
#define ID_LATEX_NEW                    33668
#define ID_LATEX_PROFILE                33669
#define ID_LATEX_PROFILE_SEL            33670
#define ID_LATEX_RUN                    33671
#define ID_LATEX_RUNANDVIEW             33672
#define ID_LATEX_STOP_BUILD             33673
#define ID_LATEX_VIEW                   33674
#define ID_URL_AUTHOR                   33700
#define ID_URL_FIRST                    33701
#define ID_URL_LAST                     33702
#define ID_URL_TCDEVELOPERSGROUP        33703
#define ID_URL_TCDICTDOWNLOAD           33704
#define ID_URL_TCERROR                  33705
#define ID_URL_TCHOME                   33706
#define ID_URL_TCNEWSLETTER             33707
#define ID_URL_TCUSERSGROUP             33708
#define ID_TOOLS_ENTRY                  33799
#define ID_USER_TOOL_FIRST              33800
#define ID_USER_TOOL_LAST               34000
#define ID_BUTTON38599                  38599
#define ID_BUTTON38600                  38600
#define ID_DOCUMENTTABS_NOTESTYLE       38601
#define ID_DOKUMENTREGISTER_AKTENORDNERSTIL 38602
#define ID_INSERT_A                     40000
#define ID_INSERT_ABSTRACT              40001
#define ID_INSERT_ACUTE                 40002
#define ID_INSERT_ALEPH                 40003
#define ID_INSERT_ALPHA                 40004
#define ID_INSERT_AMALG                 40005
#define ID_INSERT_ANGLE                 40006
#define ID_INSERT_APPROX                40007
#define ID_INSERT_ARCCOS                40008
#define ID_INSERT_ARCSIN                40009
#define ID_INSERT_ARCTAN                40010
#define ID_INSERT_ARG                   40011
#define ID_INSERT_ARRAY                 40012
#define ID_INSERT_AST                   40013
#define ID_INSERT_ASYMP                 40014
#define ID_INSERT_B                     40015
#define ID_INSERT_BACKSLASH             40016
#define ID_INSERT_BAR                   40017
#define ID_INSERT_BETA                  40018
#define ID_INSERT_BIGCAP                40019
#define ID_INSERT_BIGCIRC               40020
#define ID_INSERT_BIGCUP                40021
#define ID_INSERT_BIGODOT               40022
#define ID_INSERT_BIGOPLUS              40023
#define ID_INSERT_BIGOTIMES             40024
#define ID_INSERT_BIGSQCUP              40025
#define ID_INSERT_BIGTRIANGLEDOWN       40026
#define ID_INSERT_BIGTRIANGLEUP         40027
#define ID_INSERT_BIGUPLUS              40028
#define ID_INSERT_BIGVEE                40029
#define ID_INSERT_BIGWEDGE              40030
#define ID_INSERT_BOT                   40031
#define ID_INSERT_BOWTIE                40032
#define ID_INSERT_BREVE                 40033
#define ID_INSERT_BULLET                40034
#define ID_INSERT_CAP                   40035
#define ID_INSERT_CDOT                  40036
#define ID_INSERT_CDOTS                 40037
#define ID_INSERT_CENTER                40038
#define ID_INSERT_CHECK                 40039
#define ID_INSERT_CHI                   40040
#define ID_INSERT_CIRC                  40041
#define ID_INSERT_CLUBSUIT              40042
#define ID_INSERT_CONG                  40043
#define ID_INSERT_COPROD                40044
#define ID_INSERT_COS                   40045
#define ID_INSERT_COSH                  40046
#define ID_INSERT_COT                   40047
#define ID_INSERT_COTH                  40048
#define ID_INSERT_CSC                   40049
#define ID_INSERT_CUP                   40050
#define ID_INSERT_DAGGER                40051
#define ID_INSERT_DASHV                 40052
#define ID_INSERT_DDAGGER               40053
#define ID_INSERT_DDOT                  40054
#define ID_INSERT_DDOTS                 40055
#define ID_INSERT_DEG                   40056
#define ID_INSERT_DELTA                 40057
#define ID_INSERT_DELTA2                40058
#define ID_INSERT_DESCRIPTION           40059
#define ID_INSERT_DET                   40060
#define ID_INSERT_DIAMOND               40061
#define ID_INSERT_DIAMONDSUIT           40062
#define ID_INSERT_DIM                   40063
#define ID_INSERT_DIV                   40064
#define ID_INSERT_DOT                   40065
#define ID_INSERT_DOTEQ                 40066
#define ID_INSERT_DOWNARROW             40067
#define ID_INSERT_DOWNARROW2            40068
#define ID_INSERT_E                     40069
#define ID_INSERT_ECKIGEKLAMMER         40070
#define ID_INSERT_ECKIGEKLAMMERAUF      40071
#define ID_INSERT_ECKIGEKLAMMERZU       40072
#define ID_INSERT_ELL                   40073
#define ID_INSERT_EMPTYSET              40074
#define ID_INSERT_ENUMERATE             40075
#define ID_INSERT_EPSILON               40076
#define ID_INSERT_EQUATION              40077
#define ID_INSERT_EQUATION_ARRAY        40078
#define ID_INSERT_EQUIV                 40079
#define ID_INSERT_ETA                   40080
#define ID_INSERT_EXISTS                40081
#define ID_INSERT_EXP                   40082
#define ID_INSERT_FIGURE                40083
#define ID_INSERT_FLAT                  40084
#define ID_INSERT_FOOTNOTE              40085
#define ID_INSERT_FORALL                40086
#define ID_INSERT_FORMULA               40087
#define ID_INSERT_FORMULA_EMBEDDED      40088
#define ID_INSERT_FRAC                  40089
#define ID_INSERT_FROWN                 40090
#define ID_INSERT_GAMMA                 40091
#define ID_INSERT_GAMMA2                40092
#define ID_INSERT_GCD                   40093
#define ID_INSERT_GEQ                   40094
#define ID_INSERT_GESCHWEIFTEKLAMMERAUF 40095
#define ID_INSERT_GESCHWEIFTEKLAMMERZU  40096
#define ID_INSERT_GG                    40097
#define ID_INSERT_GRAVE                 40098
#define ID_INSERT_H                     40099
#define ID_INSERT_HAT                   40100
#define ID_INSERT_HBAR                  40101
#define ID_INSERT_HEADER                40102
#define ID_INSERT_HEARSUIT              40103
#define ID_INSERT_HOM                   40104
#define ID_INSERT_HOOKLEFTARROW         40105
#define ID_INSERT_HOOKRIGHTARROW        40106
#define ID_INSERT_I                     40107
#define ID_INSERT_IM2                   40108
#define ID_INSERT_IMATH                 40109
#define ID_INSERT_IN                    40110
#define ID_INSERT_INCLUDEGRAPHICS       40111
#define ID_INSERT_INF                   40112
#define ID_INSERT_INFTY                 40113
#define ID_INSERT_INLINEFRAC            40114
#define ID_INSERT_INT                   40115
#define ID_INSERT_IOTA                  40116
#define ID_INSERT_ITEM                  40117
#define ID_INSERT_ITEMIZE               40118
#define ID_INSERT_ITEMLABEL             40119
#define ID_INSERT_JMATH                 40120
#define ID_INSERT_K                     40121
#define ID_INSERT_KAPPA                 40122
#define ID_INSERT_KER                   40123
#define ID_INSERT_KLAMMER               40124
#define ID_INSERT_KLAMMERAUF            40125
#define ID_INSERT_KLAMMERZU             40126
#define ID_INSERT_LAMBDA                40127
#define ID_INSERT_LAMBDA2               40128
#define ID_INSERT_LDOTS                 40129
#define ID_INSERT_LEFTARROW             40130
#define ID_INSERT_LEFTARROW2            40131
#define ID_INSERT_LEFTDOUBLEVERTLINE    40132
#define ID_INSERT_LEFTECKIGEKLAMMER     40133
#define ID_INSERT_LEFTGESCHWEIFTEKLAMMER 40134
#define ID_INSERT_LEFTHARPOONDOWN       40135
#define ID_INSERT_LEFTHARPOONUP         40136
#define ID_INSERT_LEFTINVISIBLE         40137
#define ID_INSERT_LEFTKLAMMER           40138
#define ID_INSERT_LEFTLANGLE            40139
#define ID_INSERT_LEFTLCEIL             40140
#define ID_INSERT_LEFTLFLOOR            40141
#define ID_INSERT_LEFTRIGHTARROW        40142
#define ID_INSERT_LEFTRIGHTARROW2       40143
#define ID_INSERT_LEFTSLASH             40144
#define ID_INSERT_LEFTVERTLINE          40145
#define ID_INSERT_LEQ                   40146
#define ID_INSERT_LG                    40147
#define ID_INSERT_LIM                   40148
#define ID_INSERT_LIMINF                40149
#define ID_INSERT_LIMSUP                40150
#define ID_INSERT_LISTOFFIGURES         40151
#define ID_INSERT_LISTOFTABLES          40152
#define ID_INSERT_LL                    40153
#define ID_INSERT_LN                    40154
#define ID_INSERT_LOG                   40155
#define ID_INSERT_LONGLEFTARROW         40156
#define ID_INSERT_LONGLEFTARROW2        40157
#define ID_INSERT_LONGLEFTRIGHTARROW    40158
#define ID_INSERT_LONGLEFTRIGHTARROW2   40159
#define ID_INSERT_LONGMAPSTO            40160
#define ID_INSERT_LONGRIGHTARROW        40161
#define ID_INSERT_LONGRIGHTARROW2       40162
#define ID_INSERT_M2                    40163
#define ID_INSERT_MAKEGLOSSARY          40164
#define ID_INSERT_MAKEINDEX             40165
#define ID_INSERT_MAKETITLE             40166
#define ID_INSERT_MAPSTO                40167
#define ID_INSERT_MAX                   40168
#define ID_INSERT_MID                   40169
#define ID_INSERT_MIN                   40170
#define ID_INSERT_MINIPAGE              40171
#define ID_INSERT_MODELS                40172
#define ID_INSERT_MP                    40173
#define ID_INSERT_MU                    40174
#define ID_INSERT_N2                    40175
#define ID_INSERT_NABLA                 40176
#define ID_INSERT_NATURAL               40177
#define ID_INSERT_NEARROW               40178
#define ID_INSERT_NEG                   40179
#define ID_INSERT_NEQ                   40180
#define ID_INSERT_NI                    40181
#define ID_INSERT_NOTIN                 40182
#define ID_INSERT_NOTON                 40183
#define ID_INSERT_NU                    40184
#define ID_INSERT_NWARROW               40185
#define ID_INSERT_O                     40186
#define ID_INSERT_O2                    40187
#define ID_INSERT_ODOT                  40188
#define ID_INSERT_OINT                  40189
#define ID_INSERT_OMEGA                 40190
#define ID_INSERT_OMEGA2                40191
#define ID_INSERT_OMINUS                40192
#define ID_INSERT_OPLUS                 40193
#define ID_INSERT_OSLASH                40194
#define ID_INSERT_OTIMES                40195
#define ID_INSERT_OVERBRACE             40196
#define ID_INSERT_OVERLEFTARROW         40197
#define ID_INSERT_OVERLEFTRIGHTARROW    40198
#define ID_INSERT_OVERLINE              40199
#define ID_INSERT_OVERRIGHTARROW        40200
#define ID_INSERT_P2                    40201
#define ID_INSERT_PARALLEL              40202
#define ID_INSERT_PARTIAL               40203
#define ID_INSERT_PERP                  40204
#define ID_INSERT_PHI                   40205
#define ID_INSERT_PHI2                  40206
#define ID_INSERT_PI                    40207
#define ID_INSERT_PI2                   40208
#define ID_INSERT_PM                    40209
#define ID_INSERT_PR                    40210
#define ID_INSERT_PREC                  40211
#define ID_INSERT_PRECEQ                40212
#define ID_INSERT_PRIME                 40213
#define ID_INSERT_PROD                  40214
#define ID_INSERT_PROPTP                40215
#define ID_INSERT_PSI                   40216
#define ID_INSERT_PSI2                  40217
#define ID_INSERT_QUOTATION             40218
#define ID_INSERT_QUOTE                 40219
#define ID_INSERT_RE2                   40220
#define ID_INSERT_RHO                   40221
#define ID_INSERT_RIGHTARROW            40222
#define ID_INSERT_RIGHTARROW2           40223
#define ID_INSERT_RIGHTDOUBLEVERTLINE   40224
#define ID_INSERT_RIGHTECKIGEKLAMMER    40225
#define ID_INSERT_RIGHTGESCHWEIFTEKLAMMER 40226
#define ID_INSERT_RIGHTHARPOONDOWN      40227
#define ID_INSERT_RIGHTHARPOONUP        40228
#define ID_INSERT_RIGHTINVISIBLE        40229
#define ID_INSERT_RIGHTKLAMMER          40230
#define ID_INSERT_RIGHTLEFTHARPOONS     40231
#define ID_INSERT_RIGHTRANGLE           40232
#define ID_INSERT_RIGHTRCEIL            40233
#define ID_INSERT_RIGHTRFLOOR           40234
#define ID_INSERT_RIGHTVERTLINE         40235
#define ID_INSERT_SEARROW               40236
#define ID_INSERT_SEC                   40237
#define ID_INSERT_SETMINUS              40238
#define ID_INSERT_SHARP                 40239
#define ID_INSERT_SIGMA                 40240
#define ID_INSERT_SIGMA2                40241
#define ID_INSERT_SIM                   40242
#define ID_INSERT_SIMEQ                 40243
#define ID_INSERT_SIN                   40244
#define ID_INSERT_SINH                  40245
#define ID_INSERT_SLASH                 40246
#define ID_INSERT_SLOPPYPAR             40247
#define ID_INSERT_SMILE                 40248
#define ID_INSERT_SPACECLOSE            40249
#define ID_INSERT_SPACEMEDIUM           40250
#define ID_INSERT_SPACENEGATIVECLOSE    40251
#define ID_INSERT_SPACEWIDE             40252
#define ID_INSERT_SPACEWORD             40253
#define ID_INSERT_SPADESUIT             40254
#define ID_INSERT_SPITZEKLAMMERAUF      40255
#define ID_INSERT_SPITZEKLAMMERZU       40256
#define ID_INSERT_SQCAP                 40257
#define ID_INSERT_SQCUP                 40258
#define ID_INSERT_SQRT                  40259
#define ID_INSERT_SQRTEX                40260
#define ID_INSERT_SQSUBSETEQ            40261
#define ID_INSERT_SQSUPSETEQ            40262
#define ID_INSERT_STACKREL              40263
#define ID_INSERT_STAR                  40264
#define ID_INSERT_SUBSCRIPT             40265
#define ID_INSERT_SUBSET                40266
#define ID_INSERT_SUBSETEQ              40267
#define ID_INSERT_SUCC                  40268
#define ID_INSERT_SUCCEQ                40269
#define ID_INSERT_SUM                   40270
#define ID_INSERT_SUP                   40271
#define ID_INSERT_SUPERSCRIPT           40272
#define ID_INSERT_SUPERSUB              40273
#define ID_INSERT_SUPSET                40274
#define ID_INSERT_SUPSETEQ              40275
#define ID_INSERT_SURD                  40276
#define ID_INSERT_SWARROW               40277
#define ID_INSERT_T2                    40278
#define ID_INSERT_TABLE                 40279
#define ID_INSERT_TABLEOFCONTENTS       40280
#define ID_INSERT_TABULAR               40281
#define ID_INSERT_TAN                   40282
#define ID_INSERT_TANH                  40283
#define ID_INSERT_TAU                   40284
#define ID_INSERT_THEBIBLIOGRAPHY       40285
#define ID_INSERT_THETA                 40286
#define ID_INSERT_THETA2                40287
#define ID_INSERT_TILDE                 40288
#define ID_INSERT_TIMES                 40289
#define ID_INSERT_TITLEPAGE             40290
#define ID_INSERT_TITLEPROPERTIES       40291
#define ID_INSERT_TOP                   40292
#define ID_INSERT_TRIANGLE              40293
#define ID_INSERT_TRIANGLELEFT          40294
#define ID_INSERT_TRIANGLERIGHT         40295
#define ID_INSERT_UNDERBRACE            40296
#define ID_INSERT_UNDERLEFTARROW        40297
#define ID_INSERT_UNDERLEFTRIGHTARROW   40298
#define ID_INSERT_UNDERLINE             40299
#define ID_INSERT_UNDERRIGHTARROW       40300
#define ID_INSERT_UPARROW               40301
#define ID_INSERT_UPARROW2              40302
#define ID_INSERT_UPDOWNARROW           40303
#define ID_INSERT_UPDOWNARROW2          40304
#define ID_INSERT_UPLUS                 40305
#define ID_INSERT_UPSILON               40306
#define ID_INSERT_UPSILON2              40307
#define ID_INSERT_VAREPSILON            40308
#define ID_INSERT_VARPHI                40309
#define ID_INSERT_VARPI                 40310
#define ID_INSERT_VARRHO                40311
#define ID_INSERT_VARSIGMA              40312
#define ID_INSERT_VARTHETA              40313
#define ID_INSERT_VDASH                 40314
#define ID_INSERT_VDOTS                 40315
#define ID_INSERT_VEC                   40316
#define ID_INSERT_VEE                   40317
#define ID_INSERT_VERB                  40318
#define ID_INSERT_VERBATIM              40319
#define ID_INSERT_VERBATIMSTAR          40320
#define ID_INSERT_VERBSTAR              40321
#define ID_INSERT_VERSE                 40322
#define ID_INSERT_VERTDOUBLELINE        40323
#define ID_INSERT_VERTLINE              40324
#define ID_INSERT_WEDGE                 40325
#define ID_INSERT_WIDEHAT               40326
#define ID_INSERT_WIDETILDE             40327
#define ID_INSERT_WP                    40328
#define ID_INSERT_WR                    40329
#define ID_INSERT_X                     40330
#define ID_INSERT_XI                    40331
#define ID_INSERT_XI2                   40332
#define ID_INSERT_Y2                    40333
#define ID_INSERT_Z2                    40334
#define ID_INSERT_ZETA                  40335
#define ID_EDIT_BLOCKCOMMENT_INSERT     40400
#define ID_EDIT_BLOCKCOMMENT_REMOVE     40401
#define ID_EDIT_BLOCKCOMMENT_TOOGLE     40402
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     40403
#define ID_EDIT_DELETE                  40404
#define ID_EDIT_DELETE_LINE             40405
#define ID_EDIT_FIND_IN_FILES           40406
#define ID_EDIT_FIND_INCREMENTAL_BACKWARD 40407
#define ID_EDIT_FIND_INCREMENTAL_FORWARD 40408
#define ID_EDIT_FIND_PREVIOUS           40409
#define ID_EDIT_GO_BOOKMARK0            40410
#define ID_EDIT_GO_BOOKMARK1            40411
#define ID_EDIT_GO_BOOKMARK2            40412
#define ID_EDIT_GO_BOOKMARK3            40413
#define ID_EDIT_GO_BOOKMARK4            40414
#define ID_EDIT_GO_BOOKMARK5            40415
#define ID_EDIT_GO_BOOKMARK6            40416
#define ID_EDIT_GO_BOOKMARK7            40417
#define ID_EDIT_GO_BOOKMARK8            40418
#define ID_EDIT_GO_BOOKMARK9            40419
#define ID_EDIT_GOTO                    40420
#define ID_EDIT_GOTO_LAST_CHANGE        40421
#define ID_EDIT_GOTO_NEXT_BOOKMARK      40422
#define ID_EDIT_GOTO_PREV_BOOKMARK      40423
#define ID_EDIT_INDICATOR_COL           40424
#define ID_EDIT_INDICATOR_CRLF          40425
#define ID_EDIT_INDICATOR_ENCODING      40426
#define ID_EDIT_INDICATOR_POSITION      40427
#define ID_EDIT_INDICATOR_READ          40428
#define ID_EDIT_JOIN_PARAGRAPH          40429
#define ID_EDIT_NEXTGREPRESULT          40430
#define ID_EDIT_OUTSOURCE               40431
#define ID_EDIT_PREVGREPRESULT          40432
#define ID_EDIT_SEL_BIGGER_BLOCK        40433
#define ID_EDIT_SET_BREAKPOINT          40434
#define ID_EDIT_SPELL_ADD               40435
#define ID_EDIT_SPELL_IGNORE_ALL        40436
#define ID_EDIT_SPLIT_PARAGRAPH         40437
#define ID_EDIT_SWITCH_OVRMODE          40438
#define ID_EDIT_TAB                     40439
#define ID_EDIT_TOGGLE_BOOKMARK         40440
#define ID_EDIT_TOGGLE_BOOKMARK0        40441
#define ID_EDIT_TOGGLE_BOOKMARK1        40442
#define ID_EDIT_TOGGLE_BOOKMARK2        40443
#define ID_EDIT_TOGGLE_BOOKMARK3        40444
#define ID_EDIT_TOGGLE_BOOKMARK4        40445
#define ID_EDIT_TOGGLE_BOOKMARK5        40446
#define ID_EDIT_TOGGLE_BOOKMARK6        40447
#define ID_EDIT_TOGGLE_BOOKMARK7        40448
#define ID_EDIT_TOGGLE_BOOKMARK8        40449
#define ID_EDIT_TOGGLE_BOOKMARK9        40450
#define ID_EXTRAS_ADAPT                 40451
#define ID_EXTRAS_CUSTOMIZE             40452
#define ID_EXTRAS_OPTIONS               40453
#define ID_FILE_SAVE_ALL                40456
#define ID_FILEVIEW_ADD_FILES           40457
#define ID_FILEVIEW_BUILD               40458
#define ID_FILEVIEW_CLEAN               40459
#define ID_FILEVIEW_COMPILE             40460
#define ID_FILEVIEW_DELETE              40461
#define ID_FILEVIEW_INSERT_FILES        40462
#define ID_FILEVIEW_OPEN                40463
#define ID_FILEVIEW_PROPERTIES          40464
#define ID_FILEVIEW_REBUILD_ALL         40465
#define ID_FILEVIEW_RENAME              40466
#define ID_FILEVIEW_SET_MAIN            40467
#define ID_FILEVIEW_UPDATE_OUTPUT       40468
#define ID_FORMAT_BFSERIES              40469
#define ID_FORMAT_CENTER                40470
#define ID_FORMAT_EMPH                  40471
#define ID_FORMAT_FLUSHLEFT             40472
#define ID_FORMAT_FLUSHRIGHT            40473
#define ID_FORMAT_FOOTNOTESIZE          40474
#define ID_FORMAT_HUGE                  40475
#define ID_FORMAT_HUGE2                 40476
#define ID_FORMAT_ITSHAPE               40477
#define ID_FORMAT_LARGE                 40478
#define ID_FORMAT_LARGE2                40479
#define ID_FORMAT_LARGE3                40480
#define ID_FORMAT_MDSERIES              40481
#define ID_FORMAT_NORMALFONT            40482
#define ID_FORMAT_NORMALSIZE            40483
#define ID_FORMAT_RMFAMILY              40484
#define ID_FORMAT_SCRIPTSIZE            40485
#define ID_FORMAT_SCSHAPE               40486
#define ID_FORMAT_SFFAMILY              40487
#define ID_FORMAT_SLOPPYPAR             40488
#define ID_FORMAT_SLSHAPE               40489
#define ID_FORMAT_SMALL                 40490
#define ID_FORMAT_TEXTBF                40491
#define ID_FORMAT_TEXTIT                40492
#define ID_FORMAT_TEXTNORMAL            40493
#define ID_FORMAT_TEXTSC                40494
#define ID_FORMAT_TEXTSL                40495
#define ID_FORMAT_TEXTTT                40496
#define ID_FORMAT_TINY                  40497
#define ID_FORMAT_TTFAMILY              40498
#define ID_FORMAT_UPSHAPE               40499
#define ID_FORMAT_TEXT_BACK_COLOR       40500
#define ID_FORMAT_TEXT_FORE_COLOR       40501
#define ID_FILE_MRU_PROJECT_FIRST       40600
#define ID_FILE_MRU_PROJECT_LAST        40610
#define IDR_BOOKMARK_VIEW               57672

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        57673
#define _APS_NEXT_COMMAND_VALUE         40611
#define _APS_NEXT_CONTROL_VALUE         8663
#define _APS_NEXT_SYMED_VALUE           57773
#endif
#endif
