//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TeXnicCenter.rc
//
#define IDR_MAINFRAME                   1
#define IDD_PROJECT_PROPERTIES          10
#define IDS_LINE_NUMBER                 10
#define IDD_OPTIONS_LATEX               11
#define ID_VIEW_BOOKMARKS_PANE          11
#define IDS_EDIT_TEXT_NOT_FOUND         12
#define IDS_DO_NOT_SAVE                 13
#define IDR_BIB_VIEW                    14
#define IDS_UNNAMED_BOOKMARK_FORMAT     14
#define IDR_MENU1                       15
#define IDS_BIBTEX_RESULT               15
#define IDB_BITMAP2                     16
#define IDB_BITMAP3                     17
#define IDD_TRANSPARENCY                18
#define STE_SESSION_RESTORE_NOTALLWINDOWSRESTORED 19
#define IDS_SAVE_PACKAGE_AS             20
#define IDS_SELECT_PACKAGE_DIR          21
#define IDS_TOOLBAR_CUSTOMIZE           22
#define IDS_ERROR_LIST                  23
#define IDS_LOADING                     24
#define IDS_FORMAT                      25
#define IDS_ERROR_LIST_ERRORS           26
#define IDS_ERROR_LIST_WARNINGS         27
#define IDS_ERROR_LIST_BAD_BOXES        28
#define IDS_LINE                        29
#define IDS_DESCRIPTION                 30
#define IDS_FILE                        31
#define STE_LANGUAGE_NEW                32
#define STE_RESOURCE_CONFLICT           33
#define STE_LANGUAGE_GERMAN             34
#define STE_LANGUAGE_ENGLISH            35
#define STE_LANGUAGE_FRENCH             36
#define STE_CUSTOM                      37
#define IDS_ENCODING                    38
#define IDS_ENCODING_WITH_BOM           39
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 40
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 41
#define IDS_NO_LABEL_AVAILABLE          42
#define IDS_DEFINE_COLOR_NAME_PLACEHOLDER 43
#define IDS_MORE_COLORS                 44
#define IDS_AUTOMATIC                   45
#define IDS_TEXT_COLORS                 46
#define IDS_BACKGROUND_COLORS           47
#define IDS_SEARCH                      48
#define IDS_LABEL                       49
#define IDS_AUTHOR                      50
#define IDS_TITLE                       51
#define IDS_YEAR                        52
#define IDS_PUBLICATION_TYPE            53
#define IDS_PUBLISHER                   54
#define STE_OUTPUTWIZARD_DVIPDFMTYPE    55
#define IDS_WELCOME_WIZARD              56
#define IDS_WIZARD_MIKTEX_DETECTED      57
#define IDS_WIZARD_CONFIGURE_PDF        58
#define IDS_WIZARD_FINALIZE             59
#define IDS_WIZARD_WELCOME              60
#define IDS_WIZARD_CONFIGURE_PS         61
#define IDS_WIZARD_CONFIGURE_DVI        62
#define IDS_WIZARD_DISTRIBUTION_PATH    63
#define IDS_SEARCHING                   64
#define IDS_ITEMS_FOUND                 65
#define IDS_CONFIGURE_FOUND_DISTRIBUTION 66
#define IDS_RECURSIVE_INCLUSION         67
#define IDD_OPTIONS_PATHS               68
#define IDB_SPLASH                      69
#define IDD_FILE_NEW                    71
#define IDI_ICON1                       72
#define STE_COMPILER_LATEX_TYPE_EXT     73
#define STE_COMPILER_DELETE             74
#define STE_COMPILER_SET_INTYPE         75
#define STE_COMPILER_SET_OUTDESCR       76
#define STE_COMPILER_SET_COMPILER       77
#define IDD_ACTIVE_PROFILE              78
#define STE_DOCUMENT_SAVEBEFOREPROCEED  79
#define IDR_POPUP_TOOLBAR               80
#define STE_EMPTYPROJECT_TITLE          81
#define STE_EMPTYDOCUMENT_CATEGORY      82
#define STE_EMPTYDOCUMENT_DESCRIPTION   83
#define STE_DOCUMENTDIR_CREATE_ERR      84
#define STE_DOCUMENT_CANNOTCREATE       85
#define STE_PROJECT_MAINFILEEXISTS      86
#define STE_PROJECTDIR_CREATE_ERR       87
#define IDR_FORMAT_RECENTLY_USED        88
#define STE_SELECT_PROJECT_PATH         89
#define IDR_INSERT                      90
#define IDD_WINDOW                      91
#define IDD_OPTIONS_GENERIC             92
#define IDD_TABULAR                     93
#define STE_PLACEHOLDER_EXAMPLE_MAIN    94
#define IDD_FLOATOBJECT                 95
#define IDD_OUTPUTWIZARD_WELCOME        96
#define IDD_FILECLEANCONFIRM            97
#define STE_GET_PATH                    98
#define STE_FILE_EXEFILTER              99
#define IDD_ABOUTBOX                    100
#define IDD_FILE_TEMPLATE               101
#define IDB_LIGHTBULB                   102
#define IDD_TIP                         103
#define CG_IDS_TIPOFTHEDAY              104
#define CG_IDS_TIPOFTHEDAYMENU          105
#define CG_IDS_DIDYOUKNOW               106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDS_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define STE_TIP_FILE                    110
#define STE_URL_CANNOTOPEN              111
#define IDS_OPEN                        112
#define IDS_SAVE                        113
#define STE_WARNING_COUNT               114
#define STE_ENTRIES_COUNT               115
#define IDB_DOCUMENTTYPES_LARGE         118
#define STE_TAB_STRUCTURE               119
#define IDR_OUTPUT_BAR                  120
#define STE_TAB_FILES                   121
#define STE_NAVIGATIONBAR_TITLE         126
#define IDR_NAVIGATION_BAR              127
#define IDD_COMPILER_TYPE               128
#define IDR_TEXT_BACK_COLOR             129
#define IDR_TEXT_FORE_COLOR             130
#define STE_ALL_FILES_FILTER            131
#define STE_GET_PATH_TITLE              132
#define IDR_IDENTIFIERS                 133
#define STE_GRAPHIC_FILES               134
#define STE_FILE_LATEXFILTER            135
#define STE_LICENSE_FILE                136
#define IDR_POPUP_EDITOR                137
#define STE_FILE_INUSE                  138
#define STE_FILE_DICFILTER              139
#define STE_FILE_EXTERNALCHANGE         140
#define STE_FILE_EXTERNALCHANGEEX       141
#define STE_FILE_INUSE_OPEN             142
#define STE_MAINFILE_DESCRIPTION        143
#define IDD_PROJECT_NEW                 144
#define STE_TAB_ENVIRONMENTS            145
#define IDR_FILEVIEW_PROJECT            146
#define IDR_FILEVIEW_FILE               147
#define IDR_FILEVIEW_FOLDER             148
#define STE_TAB_BUILD                   149
#define IDD_ACTIVE_COMPILER_TYPE        150
#define STE_TAB_GREP_2                  151
#define IDD_ITEM_PROPERTIES             152
#define IDR_POPUP_ITEM                  153
#define STE_BIB_FILES                   154
#define STE_TEX_FILES                   155
#define STE_TAB_PARSE                   156
#define STE_APPENDIX                    157
#define STE_GRAPHICS_FILES              158
#define IDD_GRAPHIC                     159
#define STE_LATEX_START                 160
#define STE_LATEX_RESULT                161
#define STE_LATEX_START_FAILED          162
#define STE_LATEX_CANCELED              163
#define STE_LATEX_START_FAILED_EXT      164
#define STE_PLACEHOLDER_EXAMPLE_CURRENT 165
#define STE_PLACEHOLDER_EXAMPLE_MAIN_SHORT 166
#define STE_PLACEHOLDER_EXAMPLE_CURRENT_SHORT 167
#define STE_CURRENTDOC_DESCRIPTION      168
#define STE_FILECLEAN_INVALIDPATTERN    169
#define STE_CUSTOMIZE_TOOLS_ADVBTN      170
#define STE_TCP_INVALID                 171
#define STE_XML_PARSE_ERROR             172
#define STE_PROFILE_FILE_FILTER         173
#define IDS_NEWTEXTMODULE               174
#define STE_XML_INSTALLNEEDED           175
#define STE_POPUP_EDITOR                176
#define STE_POPUP_ITEM                  177
#define STE_POPUP_MAINWINDOWAREA        178
#define STE_TAB_BIBENTRIES              179
#define STE_FILE_XMLFILTER              180
#define STE_BIBTEX_ERR_QOUTEWITHINQUOTE 181
#define STE_BIBTEX_ERR_WRONGLEVELAT     182
#define STE_BIBTEX_ERR_INVALID_EOF      183
#define STE_BIBTEX_ERR_COUNT            184
#define STE_BIBTEX_ERR_MISSING_KEY      185
#define STE_BIBTEX_ERR_DUP_KEY          186
#define STE_BIBTEX_ERR_INVALID_TYPE     187
#define STE_BIBTEX_ERR_SUSPICOUS_LINE   188
#define STE_OUTPUT_TITLE                189
#define ID_START_SEARCH                 190
#define IDR_OUTPUT                      191
#define ID_METAPOST_NEW                 192
#define ID_BIBTEX_NEW                   193
#define IDR_LATEX                       194
#define STE_PROJECT_USEEXISTINGFILE     195
#define STE_PROJECT_CANNOTCREATEMAINFILE 196
#define STE_PROJECT_MAINFILENOTFOUND    197
#define STE_EMPTYPROJECT_CATEGORY       198
#define IDR_FIND                        199
#define STE_EMPTYPROJECT_DESCRIPTION    200
#define IDR_IMAGES                      201
#define STE_EMPTYDOCUMENT_TITLE         202
#define IDD_GOTO                        203
#define STE_DOCUMENT_ALREADYEXISTS      204
#define IDD_OPTIONS_FILE                205
#define IDR_HIDDEN_CMDS                 206
#define STE_PROJECT_EXISTS              207
#define STE_OPTIONS_TITLE               208
#define IDD_FILE_SAVE                   209
#define STE_OPTIONS_REQUIRES_RESTART    210
#define IDD_FILESEARCH                  211
#define IDD_HEADER                      212
#define IDR_POPUP_REGULAREXPRESSION     213
#define IDB_NAVIGATION_BAR              214
#define IDB_BITMAP1                     215
#define IDB_BUILD_ANIMATION             216
#define IDR_POPUP_PLACEHOLDER           217
#define IDB_ITEM_TYPES                  218
#define IDR_ADDITIONAL_COMMANDS         219
#define IDB_OUTPUT_BAR                  220
#define IDR_ERROR_LIST                  221
#define IDD_PROFILE                     222
#define IDD_PROFILE_NAME                223
#define STE_COMPILER_LATEX_TYPE         224
#define STE_COMPILER_FILTER             225
#define IDR_MDI_CLIENT                  226
#define IDR_POPUP_PLACEHOLDER_DIR       227
#define IDD_PACKAGE_SCAN_PROGRESS       228
#define IDB_FILE_VIEW                   229
#define STE_COMPILER_SET_OUTEXT         230
#define IDR_POPUP_MDICLIENT             231
#define STE_COMPILER_DELETE_EX          232
#define IDR_POPUP_PLACEHOLDEREX_OPT     233
#define IDD_CUSTOMIZE_TOOLS_ADV         234
#define IDD_TEXTMODULES                 235
#define IDB_TEXNICCENTER                236
#define IDD_PROFILE_EXCHANGE            237
#define IDD_PLACEHOLDER_SET             238
#define IDR_POPUP_PLACEHOLDER_OPT       239
#define STE_LATEX_REF                   240
#define STE_LATEX_PAGEREF               241
#define STE_LATEX_EQREF                 242
#define IDB_PARSE_VIEW                  243
#define STE_LATEX_CITE                  244
#define IDD_OPTIONS_SPELLING            245
#define IDR_POPUP_PLACEHOLDER_MAIN_OPT  246
#define IDR_POPUP_PLACEHOLDER_CURRENT_OPT 247
#define IDR_LATEXTYPE_YELLOW            248
#define IDD_OPTIONS_FILECLEAN           249
#define IDR_MAINFRAME_YELLOW            250
#define IDR_LATEXWIZARD_YELLOW          251
#define IDS_SPELL_CONTINUE              252
#define IDR_POPUP_PLACEHOLDEREX_NOOPT   253
#define IDD_PLACEHOLDER_SINGLE          254
#define IDS_NO_ACTION                   255
#define STE_ITEMTYPE_GENERIC            256
#define STE_ITEMTYPE_HEADER             257
#define STE_ITEMTYPE_EQUATION           258
#define STE_ITEMTYPE_QUOTE              259
#define STE_ITEMTYPE_QUOTATION          260
#define STE_ITEMTYPE_CENTER             261
#define STE_ITEMTYPE_VERSE              262
#define STE_ITEMTYPE_ITEMIZATION        263
#define STE_ITEMTYPE_ENUMERATION        264
#define STE_ITEMTYPE_DESCRIPTION        265
#define STE_ITEMTYPE_FIGURE             266
#define STE_ITEMTYPE_TABLE              267
#define STE_ITEMTYPE_UNKNOWNENV         268
#define IDR_FORMAT                      269
#define IDD_OPTIONS_EDITOR              270
#define IDS_TEXTMODULES_NONEDEFINED     271
#define STE_FLOATTITLE_INSERT_FIGURE    272
#define STE_FLOATTITLE_INSERT_TABLE     273
#define STE_FLOATTYPE_FIGURE            274
#define STE_FLOATTYPE_TABLE             275
#define STE_FLOATPREFIX_FIGURE          276
#define STE_FLOATPREFIX_TABLE           277
#define STE_TB_FIND                     278
#define IDD_DIALOG1                     279
#define IDR_STRUCTURE                   280
#define IDD_AUTOCOMPLETE                281
#define IDD_OPTIONS_TEXTFORMAT          282
#define IDD_OUTSOURCE                   285
#define STE_HEADER_PART                 288
#define STE_HEADER_CHAPTER              289
#define STE_HEADER_SECTION              290
#define STE_HEADER_SUBSECTION           291
#define STE_HEADER_SUBSUBSECTION        292
#define STE_HEADER_PARAGRAPH            293
#define STE_HEADER_SUBPARAGRAPH         294
#define STE_HEADERPREFIX_PART           295
#define STE_HEADERPREFIX_CHAPTER        296
#define STE_HEADERPREFIX_SECTION        297
#define STE_HEADERPREFIX_SUBSECTION     298
#define STE_HEADERPREFIX_SUBSUBSECTION  299
#define STE_HEADERPREFIX_PARAGRAPH      300
#define STE_HEADERPREFIX_SUBPARAGRAPH   301
#define STE_TB_MAINFRAME                304
#define STE_TB_INSERT                   305
#define STE_TB_FORMAT                   306
#define STE_TB_FORMAT_RECENTLY_USED     307
#define STE_TB_LATEX                    308
#define STE_TB_MATH                     309
#define IDR_MATH                        310
#define STE_TB_MATH1                    310
#define IDR_MATHBAR1                    311
#define STE_TB_MATH2                    311
#define IDR_MATHBAR2                    312
#define STE_TB_MATH3                    312
#define IDR_MATHBAR3                    313
#define STE_TB_MATH4                    313
#define IDR_MATHBAR4                    314
#define STE_TB_MATH5                    314
#define IDR_MATHBAR5                    315
#define STE_TB_MATH6                    315
#define IDR_MATHBAR6                    316
#define STE_TB_MATH7                    316
#define IDR_MATHBAR7                    317
#define STE_TB_MATH8                    317
#define IDR_MATHBAR8                    318
#define STE_TB_MATH9                    318
#define IDR_MATHBAR9                    319
#define STE_TB_MATH10                   319
#define IDR_MATHBAR10                   320
#define STE_TB_MATH11                   320
#define IDR_MATHBAR11                   321
#define STE_TB_MATH12                   321
#define IDR_MATHBAR12                   322
#define STE_TB_MATH13                   322
#define IDR_MATHBAR13                   323
#define STE_TB_MATH14                   323
#define IDR_MATHBAR14                   324
#define STE_TB_MATH15                   324
#define IDR_MATHBAR15                   325
#define STE_TB_MATH16                   325
#define IDR_MATHBAR16                   326
#define STE_PHSDLG_NOEXAMPLE            327
#define IDD_SCINTILLA_FINDDLGORD        328
#define IDD_SCINTILLA_REPLACEDLGORD     329
#define IDR_POPUP_ATTRIBUTE             333
#define STE_GREP_START                  336
#define STE_GREP_FAILED                 337
#define STE_GREP_CANCELED               338
#define STE_GREP_HIT                    339
#define STE_GREP_FINISHEDNOHIT          340
#define STE_GREP_FINISHED               341
#define STE_GREP_ERROR                  342
#define STE_PROJECT_CLOSE_ASK           343
#define IDS_DO_SAVE                     345
#define IDR_BIB_SEARCH                  346
#define IDR_BIB_SEARCH_OPTIONS          348
#define IDB_WIZARD                      349
#define STE_PARSE_BEGIN                 350
#define STE_PARSE_END                   351
#define STE_PARSE_PARSING               352
#define STE_PARSE_FOUND                 353
#define STE_PARSE_FOUND_UNMATCHED       354
#define STE_PARSE_RESULTS               355
#define STE_PARSE_TERMINATE             356
#define STE_FILE_EXIST                  359
#define STE_FILE_MRU_PROJECT_NONE       400
#define STE_FILE_MRU_FILE_NONE          401
#define STE_FILEFIND_BROWSEDIR          416
#define STE_NOFOLDER                    418
#define STE_FILEFIND_INVALIDEXPRESSION  419
#define STE_OUTPUTWIZARD_NOLATEX        432
#define STE_OUTPUTWIZARD_YAPCONFIG      433
#define STE_OUTPUTWIZARD_DVITYPE        434
#define STE_OUTPUTWIZARD_PSTYPE         435
#define STE_OUTPUTWIZARD_PDFTYPE        436
#define STE_OUTPUTWIZARD_OUTPUTTYPEEXISTS 437
#define STE_OUTPUTWIZARD_PDFVIAPSTYPE   438
#define STE_PROFILE_ALREADYEXISTS       448
#define STE_PROFILE_REMOVE              449
#define STE_PROFILE_UNCOMPLETE          450
#define STE_PLACEHOLDERSETS_APF         451
#define STE_PLACEHOLDERSETS_COF         452
#define STE_FILECLEAN_ERROR             453
#define STE_FILECLEAN_HNONE             454
#define STE_FILECLEAN_HCLEAN            455
#define STE_FILECLEAN_HPROTECT          456
#define STE_FILECLEAN_HPROTECTBYDEFAULT 457
#define STE_FILECLEAN_RECURSIVE         458
#define STE_FILECLEAN_NOTRECURSIVE      459
#define STE_FILECLEAN_HEAD1             460
#define STE_FILECLEAN_HEAD2             461
#define STE_FILECLEAN_HEAD3             462
#define STE_FILECLEAN_HEAD4             463
#define STE_TOOL_NOCMDLINE              464
#define STE_COLOR_AUTOMATIC             480
#define STE_COLOR_OTHERS                481
#define STE_PDICT_OPEN_ERROR            482
#define IDS_LANGUAGE                    483
#define IDS_DIALECT                     484
#define STE_DICTIONARY_OPEN_FAIL        485
#define STE_DICTIONARY_CREATE_FAIL      486
#define ID_SPELL_ERROR_FIRST            700
#define ID_SPELL_ERROR_LAST             799
#define ID_WINDOW_FIRST                 800
#define ID_WINDOW_LAST                  849
#define IDR_USER_TOOLBAR_FIRST          900
#define IDR_USER_TOOLBAR_LAST           999
#define IDC_TREE                        1001
#define IDC_TAB_CATEGORIES              1015
#define IDC_PROJECT_NAME                1017
#define IDC_PATH                        1018
#define IDC_NEW_MAIN                    1020
#define IDC_EXISTING_MAIN               1021
#define IDC_TEMPLATES                   1024
#define IDC_REMOVE_TEMPLATES            1026
#define IDC_DOCUMENTTEMPLATES           1027
#define IDC_OUTTYPE_EXT                 1034
#define IDC_VIEWER_START                1035
#define IDC_VIEWER_STARTEX              1036
#define IDC_OUTPUTTYPES                 1037
#define IDC_PROJECT_PATH                1038
#define IDC_DIR                         1040
#define IDC_MAIN_FILE                   1042
#define IDC_CAPTION                     1046
#define IDC_FLOAT_POSBOTTOM             1049
#define IDC_FLOAT_POSPAGE               1050
#define IDC_FLOAT_POSONECOL             1051
#define IDC_FLOAT_POSTWOCOL             1052
#define IDC_FLOAT_LABEL                 1055
#define IDC_FLOAT_CAPTION               1056
#define IDC_GRAPHIC_FILE                1057
#define IDC_GRAPHIC_BROWSE              1058
#define IDC_GRAPHIC_SCALE               1059
#define IDC_SPIN_SCALE                  1060
#define IDC_GRAPHIC_FLOAT               1069
#define IDC_GRAPHIC_BSCALE              1070
#define IDC_GRAPHIC_CENTER              1072
#define IDC_TABULAR_CENTER              1073
#define IDC_TABULAR_FLOAT               1074
#define IDC_TABULAR_VTOP                1075
#define IDC_TABULAR_VCENTER             1076
#define IDC_TABULAR_VBOTTOM             1077
#define IDC_GROUPPOS                    1079
#define IDC_GROUPWIDTH                  1080
#define IDC_LABELCAPTION                1081
#define IDC_LABELLABEL                  1082
#define IDC_LABELSCALE                  1083
#define IDC_OPTIONS_RESTORE_SESSION     1084
#define IDC_OPTIONS_SAVE_BEFORE_COMPILATION 1085
#define IDC_OPTIONS_SAVE_AUTOMATIC      1086
#define IDC_OPTIONS_SAVE_INTERVALL_EDIT 1087
#define IDC_OPTIONS_SAVE_INTERVALL_SPIN 1089
#define IDC_OPTIONS_SAVE_LABEL1         1090
#define IDC_OPTIONS_SAVE_LABEL2         1091
#define IDC_OPTIONS_REPLACE_QM          1092
#define IDC_OPTIONS_QM_LABEL1           1093
#define IDC_OPTIONS_QM_LABEL2           1094
#define IDC_OPTIONS_REPLACE_QM_OPEN_EDIT 1095
#define IDC_OPTIONS_REPLACE_QM_CLOSE_EDIT 1096
#define IDC_WINDOW_LIST                 1097
#define IDC_WINDOW_ACTIVATE             1098
#define IDC_WINDOW_SAVE                 1099
#define IDC_WINDOW_CLOSE                1100
#define IDC_GOTO_LINE_EDIT              1101
#define IDC_GOTO_LINE_SPIN              1102
#define IDC_URL_TEXNICCENTER            1111
#define IDC_URL_TEXNICCENTER2           1113
#define IDC_FILE_FORMAT                 1116
#define IDC_SELECT_FILEFORMAT           1116
#define IDC_OUTSOURCE_OPEN_FOREGROUND   1118
#define IDC_TYPE_DOS                    1119
#define IDC_TYPE_UNIX                   1120
#define IDC_SAVE_TYPE_DOS               1120
#define IDC_TYPE_MAC                    1121
#define IDC_SAVE_TYPE_UNIX              1121
#define IDC_SAVE_TYPE_MAC               1122
#define IDC_SEARCH_SEARCHFOR            1123
#define IDC_POPUP_REGULAREXPRESSION     1124
#define IDC_SEARCH_SEARCHTHROUGH        1125
#define IDC_SEARCH_SEARCHIN             1126
#define IDC_SEARCH_WHOLEWORDS           1128
#define IDC_SEARCH_CASESENSITIVE        1129
#define IDC_SEARCH_REGULAREXPRESSION    1130
#define IDC_SEARCH_INCLUDESUBFOLDERS    1131
#define IDC_SEARCH_OUTPUT1              1132
#define IDC_SEARCH_OUTPUT2              1133
#define IDC_EDITOR_ELEMENT              1136
#define IDC_EDITOR_ELEMENTCOLOR         1137
#define IDC_EDITOR_TABWIDTH             1138
#define IDC_OW_MIKTEXYES                1141
#define IDC_OW_MIKTEXNO                 1142
#define IDC_OW_PATH                     1143
#define IDC_OW_BROWSEPATH               1144
#define IDC_OW_VIEWERPATH               1150
#define IDC_OW_VIEWERBROWSE             1151
#define IDC_OW_VIEWERSI                 1152
#define IDC_OW_VIEWERFWSEARCH           1153
#define IDC_OW_VIEWERPOPUP              1154
#define IDC_OW_OPTLIST                  1155
#define IDC_TAB_PROFILEPAGES            1156
#define IDC_EDIT_VIEWERPATH             1158
#define IDC_BROWSE_VIEWERPATH           1159
#define IDC_EDIT_VIEWCMD                1161
#define IDC_VIEW_CMDTYPE                1162
#define IDC_VIEW_CMDTYPE1               1163
#define IDC_EDIT_VIEWDDETOPIC           1165
#define IDC_EDIT_VIEWEXCMD              1166
#define IDC_VIEWEX_CMDTYPE              1167
#define IDC_VIEWEX_CMDTYPE1             1168
#define IDC_EDIT_VIEWEXDDETOPIC         1170
#define IDC_TITLE_VIEWEXDDETOPIC        1171
#define IDC_TITLE_VIEWDDETOPIC          1172
#define IDC_EDIT_CLOSECMD               1173
#define IDC_CLOSE_CMDTYPE               1174
#define IDC_CLOSE_CMDTYPE1              1175
#define IDC_TITLE_CLOSEDDETOPIC         1177
#define IDC_EDIT_CLOSEDDETOPIC          1178
#define IDC_CLOSE_CMDTYPE2              1179
#define IDC_VIEWCMD_PLACEHOLDER         1180
#define IDC_TITLE_VIEWCMD               1181
#define IDC_STATIC_BACKGROUND           1380
#define IDC_VERSION                     1381
#define IDC_URL                         1382
#define IDC_CREDITS                     1383
#define IDC_LOGO                        1384
#define IDR_LATEXDOCTYPE                1502
#define IDR_BIBTEXDOCTYPE               1503
#define IDR_METAPOSTDOCTYPE             1504
#define IDR_LATEXPROJECTDOCTYPE         1505
#define IDB_DOCUMENTTYPES               1506
#define IDS_BIBLIOGRAPHY                1507
#define IDD_GET_PATH                    1508
#define IDS_BOOKMARK                    1509
#define IDR_LATEXWIZARD                 1510
#define IDS_FILE_LOCATION               1511
#define STE_TAB_GREP_1                  1512
#define IDC_OPTIONS_FILECLEAN_DELETE    2048
#define IDC_SEARCH_BROWSE_SEARCHIN      2049
#define IDC_OPTIONS_DEFAULT_PATH_EDIT   2051
#define IDC_OPTIONS_SAVE_NEWDOCS        2052
#define IDC_ADVTOOLS_USEOUTPUT          2053
#define IDC_GUI_LANGUAGE_COMBO          2054
#define IDC_BUTTON_SELECT_NONE          2055
#define IDC_RADIO_VIEW_TYPE             2056
#define IDC_LOOKNFEEL_COMBO             2057
#define IDC_BUTTON_SELECT_ALL           2058
#define IDC_OVERWRITECURSOR_STYLE       2059
#define IDC_OPTIONS_OPTIMIZE_FOR_VISUALLY_HANDICAPPED_USERS 2060
#define IDC_TEXTMODULES_MODULES         2061
#define IDC_PROFILE_EXPORT              2062
#define IDC_PROFILE_LIST                2063
#define IDC_REGULAR_EXPRESSION          2064
#define IDC_RADIO_VIEW_TYPE1            2065
#define IDC_OUTSOURCE_OPEN_BACKGROUND   2066
#define IDC_SELECT_ENCODING             2067
#define IDC_LIST_TEMPLATES              2068
#define IDC_TEMPLATE_LIST               2069
#define IDC_STATIC_NOTE                 2070
#define IDC_ADD_DOCUMENTTEMPLATES       2071
#define IDC_REMOVE_TYPE                 2072
#define IDC_REMOVE_DOCUMENTTEMPLATES    2073
#define IDC_TYPES                       2074
#define IDC_INTYPE_DESCR                2075
#define IDC_EDIT_TYPE                   2076
#define IDC_OUTPUT_WIZARD               2077
#define IDC_OUTTYPE_DESCR               2078
#define IDC_TITLE                       2079
#define IDC_BROWSE_MAIN_FILE            2080
#define IDC_DEPTH                       2081
#define IDC_FILE                        2082
#define IDC_COMMANDS                    2083
#define IDC_LINE                        2084
#define IDC_LABEL                       2085
#define IDC_FLOAT_POSHERE               2086
#define IDC_FLOAT_POSTOP                2087
#define IDC_COMMENT                     2088
#define IDC_INCREMENTAL_SEARCH          2089
#define IDC_REVERSE_INCREMENTAL_SEARCH  2090
#define IDC_SDRAGCOPY                   2091
#define IDC_SINGLEDRAG                  2092
#define IDC_STATIC1                     2093
#define IDC_POSTPROCESSORLIST           2094
#define IDC_VIEWEXCMD_PLACEHOLDER       2095
#define IDC_EDIT_PPEXE                  2096
#define IDC_TITLE_VIEWEXCMD             2097
#define IDC_BROWSE_POSTPROCESSOR        2098
#define IDC_CLOSECMD_PLACEHOLDER        2099
#define IDC_EDIT_PPARGUMENTS            2100
#define IDC_TITLE_CLOSECMD              2101
#define IDC_TITLE_CLOSEDDESERVER        2102
#define IDC_EDIT_PPINPUT                2103
#define IDC_EDIT_PPOUTPUT               2104
#define IDC_USELATEX                    2105
#define IDC_INSERTPH_PPARGUMENTS        2106
#define IDC_TITLE_LATEXPATH             2107
#define IDC_INSERTPH_PPINPUT            2108
#define IDC_EDIT_LATEXPATH              2109
#define IDC_INSERTPH_PPOUTPUT           2110
#define IDC_BROWSELATEX                 2111
#define IDC_TITLE_LATEXARGUMENTS        2112
#define IDC_EDIT_LATEXARGUMENTS         2113
#define IDC_LATEXPH                     2114
#define IDC_EDIT_BIBTEXPATH             2115
#define IDC_BROWSEBIBTEX                2116
#define IDC_TITLE_EXE                   2117
#define IDC_TITLE_BIBTEXARGUMENTS       2118
#define IDC_TITLE_ARGUMENTS             2119
#define IDC_EDIT_BIBTEXARGUMENTS        2120
#define IDC_TITLE_INPUT                 2121
#define IDC_BIBTEXPH                    2122
#define IDC_TITLE_OUTPUT                2123
#define IDC_EDIT_MAKEINDEXPATH          2124
#define IDC_BROWSEMAKEINDEX             2125
#define IDC_TITLE_VIEWDDESERVER         2126
#define IDC_TITLE_MAKEINDEXARGUMENTS    2127
#define IDC_EDIT_VIEWDDESERVER          2128
#define IDC_EDIT_MAKEINDEXARGUMENTS     2129
#define IDC_TITLE_VIEWEXDDESERVER       2130
#define IDC_MAKEINDEXPH                 2131
#define IDC_EDIT_VIEWEXDDESERVER        2132
#define IDC_EDIT_CLOSEDDESERVER         2133
#define IDC_PROFILE_ADD                 2134
#define IDC_PROFILE_REMOVE              2135
#define IDC_PROFILE_RENAME              2136
#define IDC_PROFILE_COPY                2137
#define IDC_EDIT_NAME                   2138
#define IDC_LIST_PROFILES               2139
#define IDC_PROFILES                    2140
#define IDC_CHECK_BIBTEX                2141
#define IDC_CHECK_MAKEINDEX             2142
#define IDC_DONTUSEBIBTEX               2143
#define IDC_TITLE_BIBTEXPATH            2144
#define IDC_DONTUSEMAKEINDEX            2145
#define IDC_EDIT_PROJECTNAME            2146
#define IDC_TITLE_MAKEINDEXPATH         2147
#define IDC_EDIT_PROJECTPATH            2148
#define IDC_BUTTON_BROWSE               2149
#define IDC_STATIC_DESCRIPTION          2150
#define IDC_BUTTON_CREATE               2151
#define IDC_EDITOR_SELECTFONT           2152
#define IDC_EDITOR_FONT                 2153
#define IDC_OPTIONS_FILETYPE            2154
#define IDC_STATIC_FORMATTITLE          2155
#define IDC_STATIC_ENCODING             2156
#define IDC_PROFILE_WIZARD              2158
#define IDC_EMPTYMESSAGE                2159
#define IDC_WINDOW                      2160
#define IDC_PROJECTTEMPLATES            2162
#define IDC_ADD_PROJECTTEMPLATES        2163
#define IDC_REMOVE_PROJECTTEMPLATES     2164
#define IDC_STOPONLATEXERROR            2165
#define IDC_OPTIONS_LANGUAGE            2166
#define IDC_OPTIONS_SPELL_ENABLE        2167
#define IDC_OPTIONS_LANGUAGE_DIALECT    2168
#define IDC_OPTIONS_SPELL_COMMENT       2169
#define IDC_OPTIONS_SPELL_SKIP_TAGS     2170
#define IDC_OPTIONS_SPELL_IGNORE_NUM    2171
#define IDC_OPTIONS_SPELL_MAINDICT      2172
#define IDC_OPTIONS_SPELL_IGNORE_ALLCAPS 2173
#define IDC_OPTIONS_SPELL_PDICT         2174
#define IDC_OPTIONS_SPELL_BROWSE        2175
#define IDC_FCCONFIRM_CLEANEDFILES      2176
#define IDC_FCCONFIRM_PROTECTEDFILES    2177
#define IDC_FCCONFIRM_LABELPROTECTED    2178
#define IDC_FCCONFIRM_LABELCLEAN        2179
#define IDC_FCCONFIRM_SHOWDIALOG        2180
#define IDC_OPTIONS_FILECLEAN_CONFIRM   2181
#define IDC_OPTIONS_FILECLEAN_LIST      2182
#define IDC_OPTIONS_FILECLEAN_NAME      2183
#define IDC_OPTIONS_FILECLEAN_PATTERN   2184
#define IDC_OPTIONS_FILECLEAN_HANDLING  2185
#define IDC_OPTIONS_FILECLEAN_RECURSIVE 2186
#define IDC_OPTIONS_FILECLEAN_PHINSERT  2187
#define IDC_OPTIONS_FILECLEAN_NEW       2188
#define IDC_BROWSE_DEFAULT_PATH         2189
#define IDC_PLACEHOLDER_SINGLE_SHORT    2190
#define IDC_PLACEHOLDER_SINGLE_FORWARD  2191
#define IDC_PLACEHOLDER_SINGLE_EXAMPLE  2192
#define IDC_PLACEHOLDER_SINGLE_PHTYPE   2193
#define IDC_PLACEHOLDER_SINGLE_WHAT     2194
#define IDC_PLACEHOLDER_SINGLE_RESULT   2195
#define IDC_OPTIONS_LANGUAGE_LOCALE     2196
#define IDC_GRAPHIC_SCALETEXTWIDTH      2197
#define IDC_PLACEHOLDER_SET_EXAMPLE     2198
#define IDC_PLACEHOLDER_SET_RESULT      2199
#define IDC_PLACEHOLDER_SET_PHTYPE      2200
#define IDC_PLACEHOLDER_SET_QUOTED      2201
#define IDC_PLACEHOLDER_SET_RELATIVE    2202
#define IDC_PLACEHOLDER_SET_SHORT       2203
#define IDC_PLACEHOLDER_SET_FORWARD     2204
#define IDC_ADVTOOLS_PROMPTARG          2205
#define IDC_ADVTOOLS_CLOSEWIN           2206
#define IDC_OPTIONS_LANGUAGE_DOWNLOAD   2207
#define IDC_INSERCURSOR_STYLE           2208
#define IDC_INSERTCURSOR_BLINK          2209
#define IDC_OVERWRITECURSOR_BLINK       2210
#define IDC_TEXTMODULES_NEWMODULE       2211
#define IDC_TEXTMODULES_DELETEMODULE    2212
#define IDC_TEXTMODULES_MENUBTN         2213
#define IDC_TEXTMODULES_NAME            2214
#define IDC_TEXTMODULES_BEFORECURSOR    2215
#define IDC_TEXTMODULES_AFTERCURSOR     2216
#define IDC_TEXTMODULES_PARAMSENABLE    2217
#define IDC_TEXTMODULES_PARAMSGROUP     2218
#define IDC_PROFILE_IMPORT              2219
#define IDC_REMOVE_DIRECTORY_SPECIFICATIONS 2220
#define IDC_STATIC_EXPORT               2221
#define IDC_STATIC_IMPORT               2222
#define IDC_BUTTON_SELECT_INVERT        2223
#define IDC_OPTIONS_REPLACE_QM_PREDEFINED_COMBO 2224
#define IDC_OPTIONS_QM_SET_LABEL        2225
#define IDC_CANCEL                      2226
#define IDC_SHOW_LINENUMBERS            2227
#define IDC_LIST                        2228
#define IDC_OPTIONS_EDITOR_WORDWRAP_STYLE 2229
#define IDC_OPTIONS_EDITOR_WORDWRAP_FIXEDCOLUMN 2230
#define IDC_OUTSOURCE_FILENAME          2231
#define IDC_OUTSOURCE_BROWSEBUTTON      2232
#define IDC_OUTSOURCE_DIRECTORY         2233
#define IDC_OUTSOURCE_CMDLEFT           2234
#define IDC_OUTSOURCE_CMDRIGHT          2235
#define IDC_OUTSOURCE_CMDINPUT          2236
#define IDC_OUTSOURCE_CMDINCLUDE        2237
#define IDC_OUTSOURCE_CMDUSERDEF        2238
#define IDC_OUTSOURCE_OPEN              2239
#define IDC_COPYRIGHT                   2240
#define IDC_SHOW_LINE_BELOW_FOLD        2241
#define IDC_SHOW_LINE_ABOVE_FOLD        2242
#define IDC_SHOW_LINE_BELOW_NO_FOLD     2243
#define IDC_SHOW_LINE_ABOVE_NO_FOLD     2244
#define IDC_USE_SPACES                  2245
#define IDC_SLIDER1                     2246
#define IDC_SLIDER_VALUE                2247
#define IDC_FOLD_COMPACT                2248
#define IDC_NEXTTIP                     2249
#define IDC_STARTUP                     2250
#define IDC_TIPSTRING                   2251
#define IDD_SPELL_CHECK                 8600
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_TEXT                   8605
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDS_EDITOP_FIRSTMODIFY          8630
#define IDS_FIND_INCREMENTAL_FORWARD    8640
#define IDS_FIND_INCREMENTAL_BACKWARD   8641
#define IDS_FIND_INCREMENTAL_FAILED     8642
#define IDS_EDIT_REPLACE_COUNT          8643
#define IDS_INCREMENTAL_SEARCH_PASSED_START_SEARCH 8644
#define IDC_SPELL_REPLACE               8650
#define IDC_SPELL_REPLACE_ALL           8651
#define IDC_SPELL_RESUME                8652
#define IDC_SPELL_IGNORE_ALL            8653
#define IDC_SPELL_TEXT                  8654
#define IDC_SPELL_IGNORE                8655
#define IDC_SPELL_NEXT                  8656
#define IDC_SPELL_SUGGEST               8657
#define IDC_SPELL_ADD                   8658
#define IDS_SPELL_IGNORE                8659
#define IDS_SPELL_UNEDIT                8660
#define IDS_SPELL_DONE                  8661
#define IDS_SPELL_NO_SUGGESTIONS        8662
#define IDD_CUSTOMIZEPAGE_EDITOR        16105
#define IDD_OUTPUTWIZARD_MIKTEX         16106
#define IDD_OUTPUTWIZARD_PATH           16107
#define IDD_OUTPUTWIZARD_DVIVIEWER      16108
#define IDD_OUTPUTWIZARD_PSVIEWER       16109
#define IDD_OUTPUTWIZARD_PDFVIEWER      16110
#define IDD_OUTPUTWIZARD_FINISH         16111
#define IDD_PROFILE_VIEWER              16113
#define IDD_PROFILE_POSTPROCESSOR       16114
#define IDD_PROFILE_LATEX               16115
#define IDD_DOCUMENT_NEW                16116
#define IDD_OPTIONS_FILECLEAN1          16117
#define IDD_ABOUTBOX1                   16117
#define ID_VIEW_BAR1                    32760
#define ID_VIEW_BAR2                    32761
#define ID_URL_TCHOME                   32768
#define ID_BIB_VIEW                     32769
#define ID_BG_UPDATE_PROJECT            32770
#define ID_TIP                          32771
#define ID_LATEX_RUN                    32772
#define ID_UPDATE_LATEX_OUTPUT          32773
#define ID_NEXT_ERROR                   32774
#define ID_PREV_ERROR                   32775
#define ID_EDIT_DELETE                  32776
#define ID_EDIT_TAB                     32777
#define ID_EDIT_SWITCH_OVRMODE          32778
#define ID_EDIT_SPELL_IGNORE_ALL        32779
#define ID_FILE_SAVE_ALL                32780
#define ID_PROJECT_MRU_PROJECT1         32781
#define ID_EDIT_FIND_IN_FILES           32782
#define ID_EDIT_GOTO                    32783
#define ID_VIEW_NAVIGATION              32784
#define ID_VIEW_OUTPUT                  32785
#define ID_PROJECT_PROPERTIES           32786
#define ID_LATEX_VIEW                   32787
#define ID_EXTRAS_ADAPT                 32788
#define ID_EXTRAS_OPTIONS               32789
#define ID_EDIT_SPELL_ADD               32790
#define ID_LATEX_FILE_NEW               32791
#define ID_LATEX_NEW                    32792
#define ID_EXTRAS_CUSTOMIZE             32793
#define ID_EDIT_FIND_PREVIOUS           32794
#define ID_NEXT_WARNING                 32795
#define ID_PREV_WARNING                 32796
#define ID_NEXT_BADBOX                  32797
#define ID_PREV_BADBOX                  32798
#define ID_PROJECT_OPEN_MAINFILE        32799
#define ID_PROJECT_PARSED               32800
#define ID_PROJECT_PARSE                32801
#define ID_IDRPOPUPITEM_GEHEZU          32802
#define ID_ITEM_GOTO                    32803
#define ID_ITEM_INSERT_REF              32804
#define ID_ITEM_INSERT_PAGEREF          32805
#define ID_ITEM_PROPERTIES              32806
#define ID_DOCUMENT_SAVED               32807
#define ID_INSERT_FORMULA_EMBEDDED      32808
#define ID_INSERT_FORMULA               32809
#define ID_INSERT_EQUATION              32810
#define ID_INSERT_EQUATION_ARRAY        32811
#define ID_INSERT_QUOTE                 32812
#define ID_INSERT_QUOTATION             32813
#define ID_INSERT_CENTER                32814
#define ID_INSERT_VERSE                 32815
#define ID_INSERT_VERBATIM              32816
#define ID_INSERT_ITEMIZE               32817
#define ID_INSERT_ENUMERATE             32818
#define ID_INSERT_DESCRIPTION           32819
#define ID_INSERT_TITLEPAGE             32820
#define ID_EDIT_SEL_BIGGER_BLOCK        32821
#define ID_INSERT_ABSTRACT              32822
#define ID_INSERT_THEBIBLIOGRAPHY       32823
#define ID_INSERT_SLOPPYPAR             32824
#define ID_INSERT_MINIPAGE              32825
#define ID_INSERT_FIGURE                32826
#define ID_INSERT_TABLE                 32827
#define ID_INSERT_ARRAY                 32828
#define ID_INSERT_TABULAR               32829
#define ID_INSERT_HEADER                32830
#define ID_INSERT_VERB                  32831
#define ID_INSERT_ITEM                  32832
#define ID_INSERT_ITEMLABEL             32833
#define ID_INSERT_TABLEOFCONTENTS       32834
#define ID_INSERT_LISTOFFIGURES         32835
#define ID_INSERT_LISTOFTABLES          32836
#define ID_INSERT_MAKEGLOSSARY          32837
#define ID_INSERT_MAKEINDEX             32838
#define ID_EDIT_TOGGLE_BOOKMARK0        32839
#define ID_INSERT_VERBSTAR              32840
#define ID_INSERT_VERBATIMSTAR          32841
#define ID_EDIT_TOGGLE_BOOKMARK1        32842
#define ID_INSERT_TITLEPROPERTIES       32843
#define ID_INSERT_MAKETITLE             32844
#define ID_INSERT_INCLUDEGRAPHICS       32845
#define ID_FORMAT_EMPH                  32846
#define ID_FORMAT_TEXTBF                32847
#define ID_FORMAT_TEXTIT                32848
#define ID_FORMAT_TEXTSL                32849
#define ID_FORMAT_TEXTNORMAL            32850
#define ID_FORMAT_RMFAMILY              32851
#define ID_FORMAT_SFFAMILY              32852
#define ID_FORMAT_TTFAMILY              32853
#define ID_FORMAT_UPSHAPE               32854
#define ID_FORMAT_ITSHAPE               32855
#define ID_FORMAT_SLSHAPE               32856
#define ID_FORMAT_SCSHAPE               32857
#define ID_FORMAT_MDSERIES              32858
#define ID_FORMAT_BFSERIES              32859
#define ID_FORMAT_SLOPPYPAR             32860
#define ID_FORMAT_FLUSHLEFT             32861
#define ID_FORMAT_CENTER                32862
#define ID_FORMAT_FLUSHRIGHT            32863
#define ID_FORMAT_TINY                  32864
#define ID_FORMAT_SCRIPTSIZE            32865
#define ID_FORMAT_FOOTNOTESIZE          32866
#define ID_FORMAT_SMALL                 32867
#define ID_FORMAT_NORMALSIZE            32868
#define ID_FORMAT_LARGE                 32869
#define ID_FORMAT_LARGE2                32870
#define ID_FORMAT_LARGE3                32871
#define ID_FORMAT_HUGE                  32872
#define ID_FORMAT_HUGE2                 32873
#define ID_INSERT_FOOTNOTE              32874
#define ID_FORMAT_NORMALFONT            32875
#define ID_INSERT_ALPHA                 32876
#define ID_INSERT_BETA                  32877
#define ID_INSERT_GAMMA                 32878
#define ID_INSERT_DELTA                 32879
#define ID_INSERT_EPSILON               32880
#define ID_INSERT_VAREPSILON            32881
#define ID_INSERT_ZETA                  32882
#define ID_INSERT_ETA                   32883
#define ID_INSERT_THETA                 32884
#define ID_INSERT_VARTHETA              32885
#define ID_INSERT_IOTA                  32886
#define ID_INSERT_KAPPA                 32887
#define ID_INSERT_LAMBDA                32888
#define ID_INSERT_MU                    32889
#define ID_INSERT_NU                    32890
#define ID_INSERT_XI                    32891
#define ID_INSERT_O                     32892
#define ID_INSERT_PI                    32893
#define ID_INSERT_VARPI                 32894
#define ID_INSERT_RHO                   32895
#define ID_INSERT_VARRHO                32896
#define ID_INSERT_SIGMA                 32897
#define ID_INSERT_VARSIGMA              32898
#define ID_INSERT_TAU                   32899
#define ID_INSERT_UPSILON               32900
#define ID_INSERT_PHI                   32901
#define ID_INSERT_VARPHI                32902
#define ID_INSERT_CHI                   32903
#define ID_INSERT_PSI                   32904
#define ID_INSERT_OMEGA                 32905
#define ID_INSERT_GAMMA2                32906
#define ID_INSERT_DELTA2                32907
#define ID_INSERT_THETA2                32908
#define ID_INSERT_LAMBDA2               32909
#define ID_INSERT_XI2                   32910
#define ID_INSERT_PI2                   32911
#define ID_INSERT_SIGMA2                32912
#define ID_INSERT_UPSILON2              32913
#define ID_INSERT_PHI2                  32914
#define ID_INSERT_PSI2                  32915
#define ID_INSERT_OMEGA2                32916
#define ID_INSERT_PM                    32917
#define ID_INSERT_MP                    32918
#define ID_INSERT_TIMES                 32919
#define ID_INSERT_DIV                   32920
#define ID_INSERT_AST                   32921
#define ID_INSERT_STAR                  32922
#define ID_INSERT_CIRC                  32923
#define ID_INSERT_BULLET                32924
#define ID_INSERT_CDOT                  32925
#define ID_INSERT_CAP                   32926
#define ID_INSERT_CUP                   32927
#define ID_INSERT_UPLUS                 32928
#define ID_INSERT_SQCAP                 32929
#define ID_INSERT_SQCUP                 32930
#define ID_INSERT_VEE                   32931
#define ID_INSERT_WEDGE                 32932
#define ID_INSERT_SETMINUS              32933
#define ID_INSERT_WR                    32934
#define ID_INSERT_DIAMOND               32935
#define ID_INSERT_BIGTRIANGLEUP         32936
#define ID_INSERT_BIGTRIANGLEDOWN       32937
#define ID_INSERT_TRIANGLELEFT          32938
#define ID_INSERT_TRIANGLERIGHT         32939
#define ID_INSERT_OPLUS                 32940
#define ID_INSERT_OMINUS                32941
#define ID_INSERT_OTIMES                32942
#define ID_INSERT_OSLASH                32943
#define ID_INSERT_ODOT                  32944
#define ID_INSERT_BIGCIRC               32945
#define ID_INSERT_DAGGER                32946
#define ID_INSERT_DDAGGER               32947
#define ID_INSERT_AMALG                 32948
#define ID_INSERT_SUM                   32949
#define ID_INSERT_PROD                  32950
#define ID_INSERT_COPROD                32951
#define ID_INSERT_INT                   32952
#define ID_INSERT_OINT                  32953
#define ID_INSERT_BIGCAP                32954
#define ID_INSERT_BIGCUP                32955
#define ID_INSERT_BIGSQCUP              32956
#define ID_INSERT_BIGVEE                32957
#define ID_INSERT_BIGWEDGE              32958
#define ID_INSERT_BIGODOT               32959
#define ID_INSERT_BIGOTIMES             32960
#define ID_INSERT_BIGOPLUS              32961
#define ID_INSERT_BIGUPLUS              32962
#define ID_INSERT_LEQ                   32963
#define ID_INSERT_PREC                  32964
#define ID_INSERT_PRECEQ                32965
#define ID_INSERT_LL                    32966
#define ID_INSERT_SUBSET                32967
#define ID_INSERT_SUBSETEQ              32968
#define ID_INSERT_SQSUBSETEQ            32969
#define ID_INSERT_IN                    32970
#define ID_INSERT_VDASH                 32971
#define ID_INSERT_GEQ                   32972
#define ID_INSERT_SUCC                  32973
#define ID_INSERT_SUCCEQ                32974
#define ID_INSERT_GG                    32975
#define ID_INSERT_SUPSET                32976
#define ID_INSERT_SUPSETEQ              32977
#define ID_INSERT_SQSUPSETEQ            32978
#define ID_INSERT_NI                    32979
#define ID_INSERT_DASHV                 32980
#define ID_INSERT_EQUIV                 32981
#define ID_INSERT_SIM                   32982
#define ID_INSERT_SIMEQ                 32983
#define ID_INSERT_ASYMP                 32984
#define ID_INSERT_APPROX                32985
#define ID_INSERT_CONG                  32986
#define ID_INSERT_NEQ                   32987
#define ID_INSERT_DOTEQ                 32988
#define ID_INSERT_NOTON                 32989
#define ID_INSERT_MODELS                32990
#define ID_INSERT_PERP                  32991
#define ID_INSERT_MID                   32992
#define ID_INSERT_PARALLEL              32993
#define ID_INSERT_BOWTIE                32994
#define ID_INSERT_SMILE                 32995
#define ID_INSERT_FROWN                 32996
#define ID_INSERT_PROPTP                32997
#define ID_INSERT_ARCCOS                32998
#define ID_INSERT_ARCSIN                32999
#define ID_INSERT_ARCTAN                33000
#define ID_INSERT_ARG                   33001
#define ID_INSERT_COS                   33002
#define ID_INSERT_COSH                  33003
#define ID_INSERT_COT                   33004
#define ID_INSERT_COTH                  33005
#define ID_INSERT_CSC                   33006
#define ID_INSERT_DEG                   33007
#define ID_INSERT_DET                   33008
#define ID_INSERT_DIM                   33009
#define ID_INSERT_EXP                   33010
#define ID_INSERT_GCD                   33011
#define ID_INSERT_HOM                   33012
#define ID_INSERT_INF                   33013
#define ID_INSERT_KER                   33014
#define ID_INSERT_LG                    33015
#define ID_INSERT_LIM                   33016
#define ID_INSERT_LIMINF                33017
#define ID_INSERT_LIMSUP                33018
#define ID_INSERT_LN                    33019
#define ID_INSERT_LOG                   33020
#define ID_INSERT_MAX                   33021
#define ID_INSERT_MIN                   33022
#define ID_INSERT_PR                    33023
#define ID_INSERT_SEC                   33024
#define ID_INSERT_SIN                   33025
#define ID_INSERT_SINH                  33026
#define ID_INSERT_SUP                   33027
#define ID_INSERT_TAN                   33028
#define ID_INSERT_TANH                  33029
#define ID_INSERT_LEFTKLAMMER           33030
#define ID_INSERT_LEFTECKIGEKLAMMER     33031
#define ID_INSERT_LEFTGESCHWEIFTEKLAMMER 33032
#define ID_INSERT_LEFTSLASH             33033
#define ID_INSERT_LEFTVERTLINE          33034
#define ID_INSERT_RIGHTKLAMMER          33035
#define ID_INSERT_RIGHTECKIGEKLAMMER    33036
#define ID_INSERT_RIGHTGESCHWEIFTEKLAMMER 33037
#define ID_INSERT_RIGHTVERTLINE         33038
#define ID_INSERT_KLAMMER               33039
#define ID_INSERT_ECKIGEKLAMMER         33040
#define ID_INSERT_KLAMMERAUF            33041
#define ID_INSERT_ECKIGEKLAMMERAUF      33042
#define ID_INSERT_GESCHWEIFTEKLAMMERAUF 33043
#define ID_INSERT_VERTLINE              33044
#define ID_INSERT_ECKIGEKLAMMERZU       33045
#define ID_INSERT_KLAMMERZU             33046
#define ID_INSERT_GESCHWEIFTEKLAMMERZU  33047
#define ID_INSERT_SPITZEKLAMMERAUF      33048
#define ID_INSERT_SPITZEKLAMMERZU       33049
#define ID_INSERT_VERTDOUBLELINE        33050
#define ID_INSERT_SLASH                 33051
#define ID_INSERT_BACKSLASH             33052
#define ID_INSERT_LEFTARROW             33053
#define ID_INSERT_LEFTARROW2            33054
#define ID_INSERT_RIGHTARROW            33055
#define ID_INSERT_RIGHTARROW2           33056
#define ID_INSERT_LEFTRIGHTARROW        33057
#define ID_INSERT_LEFTRIGHTARROW2       33058
#define ID_INSERT_MAPSTO                33059
#define ID_INSERT_HOOKLEFTARROW         33060
#define ID_INSERT_LEFTHARPOONUP         33061
#define ID_INSERT_LEFTHARPOONDOWN       33062
#define ID_INSERT_RIGHTLEFTHARPOONS     33063
#define ID_INSERT_LONGLEFTARROW         33064
#define ID_INSERT_LONGLEFTARROW2        33065
#define ID_INSERT_LONGRIGHTARROW        33066
#define ID_INSERT_LONGRIGHTARROW2       33067
#define ID_INSERT_LONGLEFTRIGHTARROW    33068
#define ID_INSERT_LONGLEFTRIGHTARROW2   33069
#define ID_INSERT_LONGMAPSTO            33070
#define ID_INSERT_HOOKRIGHTARROW        33071
#define ID_INSERT_RIGHTHARPOONUP        33072
#define ID_INSERT_RIGHTHARPOONDOWN      33073
#define ID_INSERT_UPARROW               33074
#define ID_INSERT_UPARROW2              33075
#define ID_INSERT_DOWNARROW             33076
#define ID_INSERT_DOWNARROW2            33077
#define ID_INSERT_UPDOWNARROW           33078
#define ID_INSERT_UPDOWNARROW2          33079
#define ID_INSERT_NEARROW               33080
#define ID_INSERT_SEARROW               33081
#define ID_INSERT_SWARROW               33082
#define ID_INSERT_NWARROW               33083
#define ID_INSERT_ALEPH                 33084
#define ID_INSERT_HBAR                  33085
#define ID_INSERT_IMATH                 33086
#define ID_INSERT_JMATH                 33087
#define ID_INSERT_ELL                   33088
#define ID_INSERT_WP                    33089
#define ID_INSERT_RE2                   33090
#define ID_INSERT_IM2                   33091
#define ID_INSERT_PRIME                 33092
#define ID_INSERT_EMPTYSET              33093
#define ID_INSERT_NABLA                 33094
#define ID_INSERT_SURD                  33095
#define ID_INSERT_TOP                   33096
#define ID_INSERT_BOT                   33097
#define ID_FORMAT_TEXTTT                33098
#define ID_INSERT_ANGLE                 33099
#define ID_INSERT_FORALL                33100
#define ID_INSERT_EXISTS                33101
#define ID_INSERT_NEG                   33102
#define ID_INSERT_FLAT                  33103
#define ID_INSERT_NATURAL               33104
#define ID_INSERT_SHARP                 33105
#define ID_INSERT_PARTIAL               33106
#define ID_INSERT_INFTY                 33107
#define ID_INSERT_TRIANGLE              33108
#define ID_INSERT_CLUBSUIT              33109
#define ID_INSERT_DIAMONDSUIT           33110
#define ID_INSERT_HEARSUIT              33111
#define ID_INSERT_SPADESUIT             33112
#define ID_OPTIONS_CHANGED              33113
#define ID_WINDOW_LIST                  33114
#define ID_WINDOW_LIST_MENU             33115
#define ID_EDIT_TOGGLE_BOOKMARK2        33116
#define ID_INSERT_A                     33117
#define ID_INSERT_B                     33118
#define ID_INSERT_X                     33119
#define ID_INSERT_E                     33120
#define ID_INSERT_H                     33121
#define ID_INSERT_I                     33122
#define ID_INSERT_K                     33123
#define ID_INSERT_M2                    33124
#define ID_INSERT_N2                    33125
#define ID_INSERT_O2                    33126
#define ID_INSERT_P2                    33127
#define ID_INSERT_T2                    33128
#define ID_INSERT_Y2                    33129
#define ID_INSERT_Z2                    33130
#define ID_INSERT_FRAC                  33131
#define ID_INSERT_INLINEFRAC            33132
#define ID_INSERT_SQRT                  33133
#define ID_INSERT_SQRTEX                33134
#define ID_FORMAT_TEXTSC                33135
#define ID_EDIT_TOGGLE_BOOKMARK3        33136
#define ID_EDIT_TOGGLE_BOOKMARK4        33137
#define ID_EDIT_TOGGLE_BOOKMARK5        33138
#define ID_EDIT_TOGGLE_BOOKMARK6        33139
#define ID_EDIT_TOGGLE_BOOKMARK7        33140
#define ID_EDIT_TOGGLE_BOOKMARK8        33141
#define ID_EDIT_TOGGLE_BOOKMARK9        33142
#define ID_EDIT_GO_BOOKMARK0            33143
#define ID_EDIT_GO_BOOKMARK1            33144
#define ID_EDIT_GO_BOOKMARK2            33145
#define ID_EDIT_GO_BOOKMARK3            33146
#define ID_EDIT_GO_BOOKMARK4            33147
#define ID_EDIT_GO_BOOKMARK5            33148
#define ID_EDIT_GO_BOOKMARK6            33149
#define ID_INSERT_OVERBRACE             33150
#define ID_INSERT_UNDERBRACE            33151
#define ID_INSERT_LEFTLFLOOR            33152
#define ID_INSERT_RIGHTRFLOOR           33153
#define ID_INSERT_LEFTLCEIL             33154
#define ID_INSERT_RIGHTRCEIL            33155
#define ID_INSERT_LEFTLANGLE            33156
#define ID_INSERT_RIGHTRANGLE           33157
#define ID_INSERT_LEFTDOUBLEVERTLINE    33158
#define ID_INSERT_RIGHTDOUBLEVERTLINE   33159
#define ID_INSERT_LEFTINVISIBLE         33160
#define ID_INSERT_RIGHTINVISIBLE        33161
#define ID_EDIT_GO_BOOKMARK7            33162
#define ID_EDIT_GO_BOOKMARK8            33163
#define ID_EDIT_GO_BOOKMARK9            33164
#define ID_EDIT_SET_BREAKPOINT          33165
#define ID_EDIT_TOGGLE_BOOKMARK         33166
#define ID_EDIT_GOTO_NEXT_BOOKMARK      33167
#define ID_EDIT_GOTO_PREV_BOOKMARK      33168
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     33169
#define ID_EDIT_GOTO_LAST_CHANGE        33170
#define ID_EDIT_FIND_INCREMENTAL_FORWARD 33171
#define ID_EDIT_FIND_INCREMENTAL_BACKWARD 33172
#define ID_EDIT_INDICATOR_COL           33173
#define ID_EDIT_INDICATOR_READ          33174
#define ID_EDIT_INDICATOR_CRLF          33175
#define ID_EDIT_INDICATOR_POSITION      33176
#define ID_EDIT_INDICATOR_ENCODING      33177
#define ID_INSERT_SUPERSCRIPT           33178
#define ID_INSERT_SUBSCRIPT             33179
#define ID_INSERT_SUPERSUB              33180
#define ID_INSERT_HAT                   33181
#define ID_INSERT_CHECK                 33182
#define ID_INSERT_BREVE                 33183
#define ID_INSERT_ACUTE                 33184
#define ID_INSERT_GRAVE                 33185
#define ID_INSERT_TILDE                 33186
#define ID_INSERT_NOTIN                 33187
#define ID_INSERT_BAR                   33188
#define ID_INSERT_VEC                   33189
#define ID_INSERT_DOT                   33190
#define ID_INSERT_DDOT                  33191
#define ID_INSERT_OVERLINE              33192
#define ID_INSERT_UNDERLINE             33193
#define ID_MATH1                        33194
#define ID_MATH2                        33195
#define ID_MATH3                        33196
#define ID_MATH4                        33197
#define ID_MATH5                        33198
#define ID_MATH6                        33199
#define ID_MATH7                        33200
#define ID_MATH8                        33201
#define ID_MATH9                        33202
#define ID_MATH10                       33203
#define ID_MATH11                       33204
#define ID_MATH12                       33205
#define ID_MATH13                       33206
#define ID_MATH14                       33207
#define ID_MATH15                       33208
#define ID_MATH16                       33209
#define ID_INSERT_WIDEHAT               33210
#define ID_INSERT_WIDETILDE             33211
#define ID_INSERT_STACKREL              33212
#define ID_INSERT_UNDERLEFTARROW        33213
#define ID_INSERT_UNDERRIGHTARROW       33214
#define ID_INSERT_UNDERLEFTRIGHTARROW   33215
#define ID_INSERT_OVERLEFTARROW         33216
#define ID_INSERT_OVERRIGHTARROW        33217
#define ID_INSERT_OVERLEFTRIGHTARROW    33218
#define ID_INSERT_SPACECLOSE            33219
#define ID_INSERT_SPACENEGATIVECLOSE    33220
#define ID_VIEW_MATH                    33221
#define ID_INSERT_SPACEMEDIUM           33222
#define ID_INSERT_SPACEWIDE             33223
#define ID_INSERT_SPACEWORD             33224
#define ID_INSERT_LDOTS                 33225
#define ID_INSERT_CDOTS                 33226
#define ID_INSERT_VDOTS                 33227
#define ID_INSERT_DDOTS                 33228
#define ID_URL_FIRST                    33231
#define ID_URL_AUTHOR                   33232
#define ID_URL_TCERROR                  33233
#define ID_URL_TCNEWSLETTER             33234
#define ID_URL_TCUSERSGROUP             33235
#define ID_URL_TCDEVELOPERSGROUP        33236
#define ID_URL_TCDICTDOWNLOAD           33237
#define ID_URL_LAST                     33238
#define ID_PH_MPATH                     33239
#define ID_PH_MSLASHPATH                33240
#define ID_PH_MBASE                     33241
#define ID_PH_MSLASHBASE                33242
#define ID_PH_MROOT                     33243
#define ID_PH_MDIR                      33244
#define ID_PH_MSLASHDIR                 33245
#define ID_PH_MNAME                     33246
#define ID_PH_MTITLE                    33247
#define ID_PH_MEXTENSION                33248
#define ID_PH_MSPATH                    33249
#define ID_PH_MSSLASHPATH               33250
#define ID_PH_MSBASE                    33251
#define ID_PH_MSSLASHBASE               33252
#define ID_PH_MSDIR                     33253
#define ID_VIEW_INSERT                  33254
#define ID_VIEW_LATEX                   33255
#define ID_VIEW_FORMAT                  33256
#define ID_VIEW_FORMAT_RECENTLY_USED    33257
#define ID_VIEW_MENU_BAR                33258
#define ID_VIEW_FIND                    33259
#define ID_PH_MSSLASHDIR                33260
#define ID_PH_CPATH                     33261
#define ID_PH_CSLASHPATH                33262
#define ID_PH_CBASE                     33263
#define ID_PH_CSLASHBASE                33264
#define ID_PH_CROOT                     33265
#define ID_PH_CDIR                      33266
#define ID_PH_CSLASHDIR                 33267
#define ID_PH_CNAME                     33268
#define ID_PH_CTITLE                    33269
#define ID_WINDOW_EDITOR                33270
#define ID_WINDOW_NAVIGATOR             33271
#define ID_WINDOW_STRUCTURE             33272
#define ID_WINDOW_ENVIRONMENT           33273
#define ID_WINDOW_FILES                 33274
#define ID_PH_CEXTENSION                33275
#define ID_PH_CSPATH                    33276
#define ID_PH_CSSLASHPATH               33277
#define ID_PH_CSBASE                    33278
#define ID_PH_CSSLASHBASE               33279
#define ID_PH_CSDIR                     33280
#define ID_PH_CSSLASHDIR                33281
#define ID_PH_CLINENR                   33282
#define ID_PH_PERCENT                   33283
#define ID_USER_TOOL_FIRST              33284
#define ID_USER_TOOL_LAST               33285
#define ID_PROJECT_NEW                  33286
#define ID_PROJECT_OPEN                 33287
#define ID_PROJECT_SAVE                 33288
#define ID_PROJECT_CLOSE                33289
#define ID_LATEX_FILECOMPILE            33290
#define ID_LATEX_FILEBIBTEX             33291
#define ID_LATEX_FILEMAKEINDEX          33292
#define ID_LATEX_BIBTEX                 33293
#define ID_LATEX_MAKEINDEX              33294
#define ID_PH_CSELECTION                33295
#define ID_ITEM_INSERT_LABEL            33296
#define ID_HELP_KEYMAPPING              33297
#define ID_HELP_CONTENTS                33298
#define ID_SPELL_PROJECT                33299
#define ID_VIEW_USER_TOOLBAR_FIRST      33300
#define ID_SPELL_FILE                   33301
#define ID_PHS_ALLPROJECTFILES          33302
#define ID_PHS_ALLTEXFILES              33303
#define ID_PHS_ALLBIBTEXFILES           33304
#define ID_PHS_ALLGRAPHICFILES          33305
#define ID_PHS_ALLOPENEDFILES           33306
#define ID_PHS_ALLTXCFILES              33307
#define ID_PHS_ALLFILESETS              33308
#define ID_PHS_DOLLAR                   33309
#define ID_LATEX_CLEAN                  33310
#define ID_PH_MAINOPTIONS               33311
#define ID_PH_CURRENTOPTIONS            33312
#define ID_PHS_ALLPROJECTFILES_Q        33313
#define ID_PHS_ALLOPENEDFILES_Q         33314
#define ID_PHS_ALLTEXFILES_Q            33315
#define ID_PHS_ALLBIBTEXFILES_Q         33316
#define ID_PHS_ALLGRAPHICFILES_Q        33317
#define ID_PHS_ALLTXCFILES_Q            33318
#define ID_PHS_ALLFILESETS_Q            33319
#define ID_PHS_ALLPROJECTFILES_QR       33320
#define ID_PHS_ALLOPENEDFILES_QR        33321
#define ID_PHS_ALLTEXFILES_QR           33322
#define ID_PHS_ALLBIBTEXFILES_QR        33323
#define ID_PHS_ALLGRAPHICFILES_QR       33324
#define ID_PHS_ALLTXCFILES_QR           33325
#define ID_PHS_ALLFILESETS_QR           33326
#define ID_PHS_TEST_NOOPT               33327
#define ID_PHS_TEST_OPT                 33328
#define ID_PHS_MORESETS_NOOPT           33329
#define ID_PH_MAINOPTIONS_NOOPT         33330
#define ID_PH_CURRENTOPTIONS_NOOPT      33331
#define ID_PH_MRELATIVEPATH             33332
#define ID_PH_MSLASHRELATIVEPATH        33333
#define ID_PH_MSHORTRELATIVEPATH        33334
#define ID_PH_MSSLASHRELATIVEPATH       33335
#define ID_PH_CRELATIVEPATH             33336
#define ID_PH_CSLASHRELATIVEPATH        33337
#define ID_PH_CSHORTRELATIVEPATH        33338
#define ID_PH_CSSLASHRELATIVEPATH       33339
#define ID_PHS_MORESETS_OPT             33340
#define ID_PROJECT_NEW_FROM_FILE        33341
#define ID_EDIT_BLOCKCOMMENT_TOOGLE     33342
#define ID_EDIT_BLOCKCOMMENT_INSERT     33343
#define ID_EDIT_BLOCKCOMMENT_REMOVE     33344
#define ID_TEXTMODULES_FIRST            33345
#define ID_TEXTMODULES_LAST             33346
#define ID_TEXTMODULES_DEFINE           33347
#define ID_VIEW_DOCTAB_TOP              33348
#define ID_VIEW_DOCTAB_BOTTOM           33349
#define ID_VIEW_DOCTAB_OFF              33350
#define ID_VIEW_DOCTAB_ICONS            33351
#define ID_VIEW_DOCTAB_NOTE             33352
#define ID_TOOLS_CANCEL                 33353
#define ID_LATEX_RUNANDVIEW             33354
#define ID_LATEX_FILECOMPILEANDVIEW     33355
#define ID_PACKAGE_SETUP                33356
#define ID_QUERY_COMPLETION             33357
#define ID_WINDOW_REFERENCES            33358
#define ID_WINDOW_PARSE                 33359
#define ID_WINDOW_CLOSE_ALL_BUTACTIVE   33360
#define ID_WINDOW_CLOSE_SELECTEDTAB     33361
#define ID_EDIT_OUTSOURCE               33362
#define ID_VIEW_STRUCT_PANE             33363
#define ID_VIEW_ENV_PANE                33364
#define ID_VIEW_FILES_PANE              33365
#define ID_VIEW_BIB_ENTRIES_PANE        33366
#define ID_VIEW_ERROR_LIST_PANE         33367
#define ID_VIEW_APP_LOOK_WIN_2000       33368
#define ID_VIEW_APP_LOOK_OFFICE_XP      33369
#define ID_VIEW_APP_LOOK_WIN_XP         33370
#define ID_VIEW_APP_LOOK_OFFICE_2003    33371
#define ID_VIEW_APP_LOOK_VS_2005        33372
#define ID_VIEW_APP_LOOK_OFFICE_2007_BLUE 33373
#define ID_VIEW_APP_LOOK_OFFICE_2007_BLACK 33374
#define ID_VIEW_APP_LOOK_OFFICE_2007_SILVER 33375
#define ID_VIEW_APP_LOOK_OFFICE_2007_AQUA 33376
#define ID_SHOW_ERRORS                  33377
#define ID_SHOW_WARNINGS                33378
#define ID_SHOW_BAD_BOXES               33379
#define ID_SHOW_IMAGES                  33380
#define ID_SHOW_EQUATIONS               33381
#define ID_SHOW_TABLES                  33382
#define ID_EDIT_DELETE_LINE             33383
#define ID_VIEW_DISPLAYENDLINES         33384
#define ID_VIEW_WORD_WRAP               33385
#define ID_VIEW_TOGGLE_SHOW_LINE_ENDING 33386
#define ID_VIEW_TOGGLE_WORD_WRAP        33387
#define ID_VIEW_TOGGLE_WHITE_SPACE      33388
#define ID_VIEW_LINE_ENDING             33389
#define ID_VIEW_WHITE_SPACE             33390
#define ID_SHOW_LINE_NUMBERS            33391
#define ID_VIEW_LINE_NUMBERS            33392
#define ID_VIEW_DISPLAYLINENUMBERS      33393
#define ID_EDIT_SPLIT_PARAGRAPH         33394
#define ID_EDIT_JOIN_PARAGRAPH          33395
#define ID_SEARCH_SPLITPARAGRAPH        33396
#define ID_SEARCH_JOINPARAGRAPH         33397
#define ID_VIEW_SHOW_LINE_ENDING        33398
#define ID_VIEW_USER_TOOLBAR_LAST       33399
#define ID_REGEX_FIRST                  33400
#define ID_REGEX_ANYCHAR                33401
#define ID_REGEX_CHARSET                33402
#define ID_REGEX_NOTCHARSET             33403
#define ID_REGEX_SOL                    33404
#define ID_REGEX_EOL                    33405
#define ID_REGEX_SOW                    33406
#define ID_REGEX_EOW                    33407
#define ID_REGEX_GROUP                  33408
#define ID_REGEX_OR                     33409
#define ID_REGEX_STAR                   33410
#define ID_REGEX_PLUS                   33411
#define ID_REGEX_QM                     33412
#define ID_REGEX_XTIMES                 33413
#define ID_REGEX_XTOYTIMES              33414
#define ID_REGEX_WHITESPACE             33415
#define ID_REGEX_ALNUM                  33416
#define ID_REGEX_ALPHA                  33417
#define ID_REGEX_DECDIGIT               33418
#define ID_REGEX_HEXDIGIT               33419
#define ID_REGEX_WORDCHAR               33420
#define ID_REGEX_UPPERALPHA             33421
#define ID_REGEX_LOWERALPHA             33422
#define ID_SEARCH_OPTIONS               33423
#define ID_SEARCH_EDIT                  33424
#define ID_CLEAR_SEARCH                 33425
#define ID_AUTHOR                       33426
#define ID_YEAR                         33427
#define ID_TITLE                        33428
#define ID_PUBLICATION_TYPE             33429
#define ID_PUBLISHER                    33430
#define ID_VIEW_INDENTATION_GUIDES      33431
#define ID_VIEW_INDENTATIONGUIDES       33432
#define ID_VIEW_TRANSPARENCY            33433
#define ID_NONE                         33434
#define ID_FORMAT_TEXT_BACK_COLOR       33435
#define ID_FORMAT_TEXT_FORE_COLOR       33436
#define ID_VIEW_BUILD_PANE              33437
#define ID_VIEW_GREP_1_PANE             33438
#define ID_VIEW_GREP_2_PANE             33439
#define ID_VIEW_PARSE_PANE              33440
#define ID_REGEX_LAST                   33499
#define ID_WINDOW_OUTPUT                33500
#define ID_WINDOW_BUILDRESULT           33501
#define ID_WINDOW_GREP1                 33502
#define ID_WINDOW_GREP2                 33503
#define ID_EDIT_NEXTGREPRESULT          33504
#define ID_EDIT_PREVGREPRESULT          33505
#define ID_APP_LICENSE                  33507
#define ID_TOOLS_ENTRY                  33508
#define ID_WINDOW_NEXT                  33509
#define ID_WINDOW_PREVIOUS              33510
#define ID_WINDOW_CLOSE_ALL             33511
#define ID_LATEX_PROFILE                33512
#define ID_LATEX_EDITPROFILES           33513
#define ID_LATEX_PROFILE_SEL            33514
#define ID_VIEW_FULLSCREEN              33525
#define ID_FILEVIEW_BUILD               33530
#define ID_FILEVIEW_CLEAN               33531
#define ID_FILEVIEW_REBUILD_ALL         33532
#define ID_FILEVIEW_PROPERTIES          33533
#define ID_FILEVIEW_ADD_FILES           33534
#define ID_FILEVIEW_COMPILE             33535
#define ID_FILEVIEW_SET_MAIN            33536
#define ID_FILEVIEW_DELETE              33537
#define ID_FILEVIEW_RENAME              33538
#define ID_FILEVIEW_INSERT_FILES        33539
#define ID_FILEVIEW_OPEN                33540
#define ID_FILEVIEW_UPDATE_OUTPUT       33551
#define ID_LATEX_STOP_BUILD             33553
#define ID_BUTTON38599                  38599
#define ID_BUTTON38600                  38600
#define ID_DOCUMENTTABS_NOTESTYLE       38601
#define ID_DOKUMENTREGISTER_AKTENORDNERSTIL 38602
#define IDR_TOOLBAR1                    57672
#define IDR_BOOKMARK_VIEW               57672
#define IDB_BITMAP4                     57678
#define ID_FILE_MRU_PROJECT_FIRST       58080
#define ID_FILE_MRU_PROJECT_LAST        58090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        57679
#define _APS_NEXT_COMMAND_VALUE         38603
#define _APS_NEXT_CONTROL_VALUE         1385
#define _APS_NEXT_SYMED_VALUE           57772
#endif
#endif
